const allPlayers = {
  "프리미어리그": [
    // 맨체스터 시티 FC 2025-26 시즌 스쿼드 명단
    { name: "James Trafford", nameKo: "제임스 트래포드", nationality: "잉글랜드", team: "맨체스터 시티", position: "GK", birthYear: 2002, number: 1 },
    { name: "Rúben Dias", nameKo: "후벵 디아스", nationality: "포르투갈", team: "맨체스터 시티", position: "DF", birthYear: 1997, number: 3 },
    { name: "Tijjani Reijnders", nameKo: "티자니 라인더르스", nationality: "네덜란드", team: "맨체스터 시티", position: "MF", birthYear: 1998, number: 4 },
    { name: "John Stones", nameKo: "존 스톤스", nationality: "잉글랜드", team: "맨체스터 시티", position: "DF", birthYear: 1994, number: 5 },
    { name: "Nathan Aké", nameKo: "네이선 아케", nationality: "네덜란드", team: "맨체스터 시티", position: "DF", birthYear: 1995, number: 6 },
    { name: "Omar Marmoush", nameKo: "오마르 마르무시", nationality: "이집트", team: "맨체스터 시티", position: "FW", birthYear: 1999, number: 7 },
    { name: "Mateo Kovačić", nameKo: "마테오 코바치치", nationality: "크로아티아", team: "맨체스터 시티", position: "MF", birthYear: 1994, number: 8 },
    { name: "Erling Haaland", nameKo: "엘링 홀란드", nationality: "노르웨이", team: "맨체스터 시티", position: "FW", birthYear: 2000, number: 9 },
    { name: "Rayan Cherki", nameKo: "라얀 셰르키", nationality: "프랑스", team: "맨체스터 시티", position: "MF", birthYear: 2003, number: 10 },
    { name: "Jérémy Doku", nameKo: "제레미 도쿠", nationality: "벨기에", team: "맨체스터 시티", position: "MF", birthYear: 2002, number: 11 },
    { name: "Marcus Bettinelli", nameKo: "마커스 베티넬리", nationality: "잉글랜드", team: "맨체스터 시티", position: "GK", birthYear: 1992, number: 13 },
    { name: "Nico González", nameKo: "니코 곤살레스", nationality: "스페인", team: "맨체스터 시티", position: "MF", birthYear: 2002, number: 14 },
    { name: "Rodrigo", nameKo: "로드리", nationality: "스페인", team: "맨체스터 시티", position: "MF", birthYear: 1996, number: 16 },
    { name: "Stefan Ortega Moreno", nameKo: "슈테판 오르테가", nationality: "독일", team: "맨체스터 시티", position: "GK", birthYear: 1992, number: 18 },
    { name: "Bernardo Silva", nameKo: "베르나르두 실바", nationality: "포르투갈", team: "맨체스터 시티", position: "MF", birthYear: 1994, number: 20 },
    { name: "Rayan Aït-Nouri", nameKo: "라얀 아이트누리", nationality: "알제리", team: "맨체스터 시티", position: "DF", birthYear: 2001, number: 21 },
    { name: "Joško Gvardiol", nameKo: "요슈코 그바르디올", nationality: "크로아티아", team: "맨체스터 시티", position: "DF", birthYear: 2002, number: 24 },
    { name: "Gianluigi Donnarumma", nameKo: "잔루이지 돈나룸마", nationality: "이탈리아", team: "맨체스터 시티", position: "GK", birthYear: 1999, number: 25 },
    { name: "Savinho", nameKo: "사비뉴", nationality: "브라질", team: "맨체스터 시티", position: "MF", birthYear: 2004, number: 26 },
    { name: "Matheus Nunes", nameKo: "마테우스 누네스", nationality: "포르투갈", team: "맨체스터 시티", position: "MF", birthYear: 1998, number: 27 },
    { name: "Nico O'Reilly", nameKo: "니코 오라일리", nationality: "잉글랜드", team: "맨체스터 시티", position: "MF", birthYear: 2005, number: 33 },
    { name: "Antoine Semenyo", nameKo: "앙투안 세메뇨", nationality: "가나", team: "맨체스터 시티", position: "MF", birthYear: 2000, number: 42 },
    { name: "Kalvin Phillips", nameKo: "칼빈 필립스", nationality: "잉글랜드", team: "맨체스터 시티", position: "MF", birthYear: 1995, number: 44 },
    { name: "Abdukodir Khusanov", nameKo: "압두코디르 후사노프", nationality: "우즈베키스탄", team: "맨체스터 시티", position: "DF", birthYear: 2004, number: 45 },
    { name: "Phil Foden", nameKo: "필 포든", nationality: "잉글랜드", team: "맨체스터 시티", position: "MF", birthYear: 2000, number: 47 },
    { name: "Oscar Bobb", nameKo: "오스카르 보브", nationality: "노르웨이", team: "맨체스터 시티", position: "MF", birthYear: 2003, number: 52 },
    { name: "Rico Lewis", nameKo: "리코 루이스", nationality: "잉글랜드", team: "맨체스터 시티", position: "DF", birthYear: 2004, number: 82 },
    // 리버풀
    // 리버풀 FC 최종 스쿼드
    [
  { name: "Alisson Becker", nameKo: "알리송 베케르", nationality: "브라질", team: "리버풀", position: "GK", birthYear: 1992, number: 1 },
  { name: "Joe Gomez", nameKo: "조 고메즈", nationality: "잉글랜드", team: "리버풀", position: "DF", birthYear: 1997, number: 2 },
  { name: "Wataru Endo", nameKo: "엔도 와타루", nationality: "일본", team: "리버풀", position: "MF", birthYear: 1993, number: 3 },
  { name: "Virgil van Dijk", nameKo: "버질 판데이크", nationality: "네덜란드", team: "리버풀", position: "DF", birthYear: 1991, number: 4 },
  { name: "Ibrahima Konaté", nameKo: "이브라히마 코나테", nationality: "프랑스", team: "리버풀", position: "DF", birthYear: 1999, number: 5 },
  { name: "Miloš Kerkez", nameKo: "밀로시 케르케즈", nationality: "헝가리", team: "리버풀", position: "DF", birthYear: 2003, number: 6 },
  { name: "Florian Wirtz", nameKo: "플로리안 비르츠", nationality: "독일", team: "리버풀", position: "MF", birthYear: 2003, number: 7 },
  { name: "Dominik Szoboszlai", nameKo: "도미니크 소보슬라이", nationality: "헝가리", team: "리버풀", position: "MF", birthYear: 2000, number: 8 },
  { name: "Alexander Isak", nameKo: "알렉산데르 이사크", nationality: "스웨덴", team: "리버풀", position: "FW", birthYear: 1999, number: 9 },
  { name: "Alexis Mac Allister", nameKo: "알렉시스 맥 알리스터", nationality: "아르헨티나", team: "리버풀", position: "MF", birthYear: 1998, number: 10 },
  { name: "Mohamed Salah", nameKo: "모하메드 살라", nationality: "이집트", team: "리버풀", position: "FW", birthYear: 1992, number: 11 },
  { name: "Conor Bradley", nameKo: "코너 브래들리", nationality: "북아일랜드", team: "리버풀", position: "DF", birthYear: 2003, number: 12 },
  { name: "Federico Chiesa", nameKo: "페데리코 키에사", nationality: "이탈리아", team: "리버풀", position: "MF", birthYear: 1997, number: 14 },
  { name: "Giovanni Leoni", nameKo: "조반니 레오니", nationality: "이탈리아", team: "리버풀", position: "DF", birthYear: 2006, number: 15 },
  { name: "Curtis Jones", nameKo: "커티스 존스", nationality: "잉글랜드", team: "리버풀", position: "MF", birthYear: 2001, number: 17 },
  { name: "Cody Gakpo", nameKo: "코디 각포", nationality: "네덜란드", team: "리버풀", position: "FW", birthYear: 1999, number: 18 },
  { name: "Hugo Ekitiké", nameKo: "위고 에키티케", nationality: "프랑스", team: "리버풀", position: "FW", birthYear: 2002, number: 22 },
  { name: "Giorgi Mamardashvili", nameKo: "기오르기 마마르다슈빌리", nationality: "조지아", team: "리버풀", position: "GK", birthYear: 2000, number: 25 },
  { name: "Andrew Robertson", nameKo: "앤드루 로버트슨", nationality: "스코틀랜드", team: "리버풀", position: "DF", birthYear: 1994, number: 26 },
  { name: "Freddy Woodman", nameKo: "프레디 우드먼", nationality: "잉글랜드", team: "리버풀", position: "GK", birthYear: 1997, number: 28 },
  { name: "Jeremie Frimpong", nameKo: "제레미 프림퐁", nationality: "네덜란드", team: "리버풀", position: "DF", birthYear: 2000, number: 30 },
  { name: "Ryan Gravenberch", nameKo: "라이언 흐라벤베르흐", nationality: "네덜란드", team: "리버풀", position: "MF", birthYear: 2002, number: 38 },
  { name: "Calvin Ramsay", nameKo: "캘빈 램지", nationality: "스코틀랜드", team: "리버풀", position: "DF", birthYear: 2003, number: 47 },
  // 아스널
    // 아스날 FC 2025-26 시즌 스쿼드 명단
    { name: "David Raya", nameKo: "다비드 라야", nationality: "스페인", team: "아스날", position: "GK", birthYear: 1995, number: 1 },
    { name: "William Saliba", nameKo: "윌리엄 살리바", nationality: "프랑스", team: "아스날", position: "DF", birthYear: 2001, number: 2 },
    { name: "Cristhian Mosquera", nameKo: "크리스티안 모스케라", nationality: "스페인", team: "아스날", position: "DF", birthYear: 2004, number: 3 },
    { name: "Ben White", nameKo: "벤 화이트", nationality: "잉글랜드", team: "아스날", position: "DF", birthYear: 1997, number: 4 },
    { name: "Piero Hincapié", nameKo: "피에로 잉카피에", nationality: "에콰도르", team: "아스날", position: "DF", birthYear: 2002, number: 5 },
    { name: "Gabriel Magalhães", nameKo: "가브리에우 마갈량이스", nationality: "브라질", team: "아스날", position: "DF", birthYear: 1997, number: 6 },
    { name: "Bukayo Saka", nameKo: "부카요 사카", nationality: "잉글랜드", team: "아스날", position: "FW", birthYear: 2001, number: 7 },
    { name: "Martin Ødegaard", nameKo: "마르틴 외데고르", nationality: "노르웨이", team: "아스날", position: "MF", birthYear: 1998, number: 8 },
    { name: "Gabriel Jesus", nameKo: "가브리에우 제주스", nationality: "브라질", team: "아스날", position: "FW", birthYear: 1997, number: 9 },
    { name: "Eberechi Eze", nameKo: "에베레치 에제", nationality: "잉글랜드", team: "아스날", position: "FW", birthYear: 1998, number: 10 },
    { name: "Gabriel Martinelli", nameKo: "가브리에우 마르티넬리", nationality: "브라질", team: "아스날", position: "FW", birthYear: 2001, number: 11 },
    { name: "Jurriën Timber", nameKo: "위리엔 팀버르", nationality: "네덜란드", team: "아스날", position: "DF", birthYear: 2001, number: 12 },
    { name: "Kepa Arrizabalaga", nameKo: "케파 아리사발라가", nationality: "스페인", team: "아스날", position: "GK", birthYear: 1994, number: 13 },
    { name: "Viktor Gyökeres", nameKo: "빅토르 요케레스", nationality: "스웨덴", team: "아스날", position: "FW", birthYear: 1998, number: 14 },
    { name: "Christian Nørgaard", nameKo: "크리스티안 뇌르고르", nationality: "덴마크", team: "아스날", position: "MF", birthYear: 1994, number: 16 },
    { name: "Leandro Trossard", nameKo: "레안드로 트로사르", nationality: "벨기에", team: "아스날", position: "FW", birthYear: 1994, number: 19 },
    { name: "Noni Madueke", nameKo: "노니 마두에케", nationality: "잉글랜드", team: "아스날", position: "FW", birthYear: 2002, number: 20 },
    { name: "Ethan Nwaneri", nameKo: "에단 은와네리", nationality: "잉글랜드", team: "아스날", position: "MF", birthYear: 2007, number: 22 },
    { name: "Mikel Merino", nameKo: "미켈 메리노", nationality: "스페인", team: "아스날", position: "MF", birthYear: 1996, number: 23 },
    { name: "Kai Havertz", nameKo: "카이 하베르츠", nationality: "독일", team: "아스날", position: "FW", birthYear: 1999, number: 29 },
    { name: "Riccardo Calafiori", nameKo: "리카르도 칼라피오리", nationality: "이탈리아", team: "아스날", position: "DF", birthYear: 2002, number: 33 },
    { name: "Martin Zubimendi", nameKo: "마르틴 수비멘디", nationality: "스페인", team: "아스날", position: "MF", birthYear: 1999, number: 36 },
    { name: "Declan Rice", nameKo: "데클란 라이스", nationality: "잉글랜드", team: "아스날", position: "MF", birthYear: 1999, number: 41 },
    { name: "Myles Lewis-Skelly", nameKo: "마일스 루이스스켈리", nationality: "잉글랜드", team: "아스날", position: "MF", birthYear: 2006, number: 49 },
    { name: "Max Dowman", nameKo: "맥스 다우먼", nationality: "잉글랜드", team: "아스날", position: "FW", birthYear: 2009, number: 56 },
    // 맨체스터 유나이티드
    // 맨체스터 유나이티드 2025-26 시즌 스쿼드 (이미지 대조 완료)
   
  { name: "Altay Bayındır", nameKo: "알타이 바인디르", nationality: "터키", team: "맨유", position: "GK", birthYear: 1998, number: 1 },
  { name: "Diogo Dalot", nameKo: "디오구 달로", nationality: "포르투갈", team: "맨유", position: "RB", birthYear: 1999, number: 2 },
  { name: "Noussair Mazraoui", nameKo: "누사이르 마즈라위", nationality: "모로코", team: "맨유", position: "RB", birthYear: 1997, number: 3 },
  { name: "Matthijs de Ligt", nameKo: "마테이스 더리흐트", nationality: "네덜란드", team: "맨유", position: "CB", birthYear: 1999, number: 4 },
  { name: "Harry Maguire", nameKo: "해리 매과이어", nationality: "잉글랜드", team: "맨유", position: "CB", birthYear: 1993, number: 5 },
  { name: "Lisandro Martínez", nameKo: "리산드로 마르티네스", nationality: "아르헨티나", team: "맨유", position: "CB", birthYear: 1998, number: 6 },
  { name: "Mason Mount", nameKo: "메이슨 마운트", nationality: "잉글랜드", team: "맨유", position: "CAM", birthYear: 1999, number: 7 },
  { name: "Bruno Fernandes", nameKo: "브루노 페르난데스", nationality: "포르투갈", team: "맨유", position: "CAM", birthYear: 1994, number: 8 },
  { name: "Matheus Cunha", nameKo: "마테우스 쿠냐", nationality: "브라질", team: "맨유", position: "ST", birthYear: 1999, number: 10 },
  { name: "Joshua Zirkzee", nameKo: "조슈아 지르크지", nationality: "네덜란드", team: "맨유", position: "ST", birthYear: 2001, number: 11 },
  { name: "Tyrell Malacia", nameKo: "타이렐 말라시아", nationality: "네덜란드", team: "맨유", position: "LB", birthYear: 1999, number: 12 },
  { name: "Patrick Dorgu", nameKo: "패트릭 도르구", nationality: "덴마크", team: "맨유", position: "LWB", birthYear: 2004, number: 13 },
  { name: "Leny Yoro", nameKo: "레니 요로", nationality: "프랑스", team: "맨유", position: "CB", birthYear: 2005, number: 15 },
  { name: "Amad Diallo", nameKo: "아마드 디알로", nationality: "코트디부아르", team: "맨유", position: "RW", birthYear: 2002, number: 16 },
  { name: "Casemiro", nameKo: "카세미루", nationality: "브라질", team: "맨유", position: "CDM", birthYear: 1992, number: 18 },
  { name: "Bryan Mbeumo", nameKo: "브라이언 음뵈모", nationality: "카메룬", team: "맨유", position: "RW", birthYear: 1999, number: 19 },
  { name: "Tom Heaton", nameKo: "톰 히튼", nationality: "잉글랜드", team: "맨유", position: "GK", birthYear: 1986, number: 22 },
  { name: "Luke Shaw", nameKo: "루크 쇼", nationality: "잉글랜드", team: "맨유", position: "LB", birthYear: 1995, number: 23 },
  { name: "Manuel Ugarte", nameKo: "마누엘 우가르테", nationality: "우루과이", team: "맨유", position: "CM", birthYear: 2001, number: 25 },
  { name: "Ayden Heaven", nameKo: "에이든 헤븐", nationality: "잉글랜드", team: "맨유", position: "CB", birthYear: 2006, number: 26 },
  { name: "Benjamin Šeško", nameKo: "벤야민 셰슈코", nationality: "슬로베니아", team: "맨유", position: "ST", birthYear: 2003, number: 30 },
  { name: "Senne Lammens", nameKo: "센네 라멘스", nationality: "벨기에", team: "맨유", position: "GK", birthYear: 2002, number: 31 },
  { name: "Chido Obi-Martin", nameKo: "치도 오비-마틴", nationality: "덴마크", team: "맨유", position: "ST", birthYear: 2007, number: 32 },
  { name: "Tyler Fredricson", nameKo: "타일러 프레드릭슨", nationality: "잉글랜드", team: "맨유", position: "CB", birthYear: 2005, number: 33 },
  { name: "Diego León", nameKo: "디에고 레온", nationality: "파라과이", team: "맨유", position: "LB", birthYear: 2007, number: 35 },
  { name: "Kobbie Mainoo", nameKo: "코비 마이누", nationality: "잉글랜드", team: "맨유", position: "CM", birthYear: 2005, number: 37 },

    // 첼시
    // 첼시 FC 2025-26 시즌 스쿼드 명단 (이미지 기준 최종)
    
  // 첼시 (Chelsea FC)
  { name: "Robert Sánchez", nameKo: "로베르트 산체스", nationality: "스페인", team: "첼시", position: "GK", birthYear: 1997, number: 1 },
  { name: "Marc Cucurella", nameKo: "마르크 쿠쿠렐라", nationality: "스페인", team: "첼시", position: "LB", birthYear: 1998, number: 3 },
  { name: "Tosin Adarabioyo", nameKo: "토신 아다라비오요", nationality: "잉글랜드", team: "첼시", position: "CB", birthYear: 1997, number: 4 },
  { name: "Benoît Badiashile", nameKo: "브누아 바디아실", nationality: "프랑스", team: "첼시", position: "CB", birthYear: 2001, number: 5 },
  { name: "Levi Colwill", nameKo: "리바이 콜윌", nationality: "잉글랜드", team: "첼시", position: "CB", birthYear: 2003, number: 6 },
  { name: "Pedro Neto", nameKo: "페드로 네투", nationality: "포르투갈", team: "첼시", position: "RW", birthYear: 2000, number: 7 },
  { name: "Enzo Fernández", nameKo: "엔초 페르난데스", nationality: "아르헨티나", team: "첼시", position: "CM", birthYear: 2001, number: 8 },
  { name: "Liam Delap", nameKo: "리암 델랍", nationality: "잉글랜드", team: "첼시", position: "ST", birthYear: 2003, number: 9 },
  { name: "Cole Palmer", nameKo: "콜 파머", nationality: "잉글랜드", team: "첼시", position: "CAM", birthYear: 2002, number: 10 },
  { name: "Jamie Gittens", nameKo: "제이미 기튼스", nationality: "잉글랜드", team: "첼시", position: "LW", birthYear: 2004, number: 11 },
  { name: "Filip Jörgensen", nameKo: "필립 요르겐센", nationality: "덴마크", team: "첼시", position: "GK", birthYear: 2002, number: 12 },
  { name: "Dário Essugo", nameKo: "다리우 이수구", nationality: "포르투갈", team: "첼시", position: "CDM", birthYear: 2005, number: 14 },
  { name: "Nicolas Jackson", nameKo: "니콜라 잭슨", nationality: "세네갈", team: "첼시", position: "ST", birthYear: 2001, number: 15 },
  { name: "Andrey Santos", nameKo: "안드레이 산투스", nationality: "브라질", team: "첼시", position: "CM", birthYear: 2004, number: 17 },
  { name: "Christopher Nkunku", nameKo: "크리스토퍼 은쿤쿠", nationality: "프랑스", team: "첼시", position: "CAM", birthYear: 1997, number: 18 },
  { name: "Mamadou Sarr", nameKo: "마마두 사르", nationality: "프랑스", team: "첼시", position: "CB", birthYear: 2005, number: 19 },
  { name: "João Pedro", nameKo: "조앙 페드루", nationality: "브라질", team: "첼시", position: "ST", birthYear: 2001, number: 20 },
  { name: "Jorrel Hato", nameKo: "요렐 하토", nationality: "네덜란드", team: "첼시", position: "LB", birthYear: 2006, number: 21 },
  { name: "Trevoh Chalobah", nameKo: "트레보 찰로바", nationality: "잉글랜드", team: "첼시", position: "CB", birthYear: 1999, number: 23 },
  { name: "Reece James", nameKo: "리스 제임스", nationality: "잉글랜드", team: "첼시", position: "RB", birthYear: 1999, number: 24 },
  { name: "Moisés Caicedo", nameKo: "모이세스 카이세도", nationality: "에콰도르", team: "첼시", position: "CDM", birthYear: 2001, number: 25 },
  { name: "Malo Gusto", nameKo: "말로 귀스토", nationality: "프랑스", team: "첼시", position: "RB", birthYear: 2003, number: 27 },
  { name: "Wesley Fofana", nameKo: "웨슬리 포파나", nationality: "프랑스", team: "첼시", position: "CB", birthYear: 2000, number: 29 },
  { name: "Aaron Anselmino", nameKo: "아론 안셀미노", nationality: "아르헨티나", team: "첼시", position: "CB", birthYear: 2005, number: 30 },
  { name: "Tyrique George", nameKo: "타이리크 조지", nationality: "잉글랜드", team: "첼시", position: "LW", birthYear: 2006, number: 32 },
  { name: "Josh Acheampong", nameKo: "조슈아 아체암퐁", nationality: "잉글랜드", team: "첼시", position: "RB", birthYear: 2006, number: 34 },
  { name: "Marc Guiu", nameKo: "마르크 기우", nationality: "스페인", team: "첼시", position: "ST", birthYear: 2006, number: 38 },
  { name: "Mike Penders", nameKo: "마이크 펜더르스", nationality: "벨기에", team: "첼시", position: "GK", birthYear: 2005, number: 39 },
  { name: "Facundo Buonanotte", nameKo: "파쿤도 부오나노테", nationality: "아르헨티나", team: "첼시", position: "CAM", birthYear: 2004, number: 40 },
  { name: "Estêvão", nameKo: "에스테방", nationality: "브라질", team: "첼시", position: "RW", birthYear: 2007, number: 41 },
  { name: "Gabriel Slonina", nameKo: "가브리엘 슬로니나", nationality: "미국", team: "첼시", position: "GK", birthYear: 2004, number: 44 },
  { name: "Roméo Lavia", nameKo: "로메오 라비아", nationality: "벨기에", team: "첼시", position: "CDM", birthYear: 2004, number: 45 },
  { name: "Alejandro Garnacho", nameKo: "알레한드로 가르나초", nationality: "아르헨티나", team: "첼시", position: "LW", birthYear: 2004, number: 49 },

  // 토트넘 (Tottenham Hotspur)
  { name: "Guglielmo Vicario", nameKo: "굴리엘모 비카리오", nationality: "이탈리아", team: "토트넘", position: "GK", birthYear: 1996, number: 1 },
  { name: "Radu Drăgușin", nameKo: "라두 드라구신", nationality: "루마니아", team: "토트넘", position: "CB", birthYear: 2002, number: 3 },
  { name: "Kevin Danso", nameKo: "케빈 단소", nationality: "오스트리아", team: "토트넘", position: "CB", birthYear: 1998, number: 4 },
  { name: "João Palhinha", nameKo: "조앙 팔리냐", nationality: "포르투갈", team: "토트넘", position: "CDM", birthYear: 1995, number: 6 },
  { name: "Xavi Simons", nameKo: "사비 시몬스", nationality: "네덜란드", team: "토트넘", position: "CAM", birthYear: 2003, number: 7 },
  { name: "Yves Bissouma", nameKo: "이브 비수마", nationality: "말리", team: "토트넘", position: "CDM", birthYear: 1996, number: 8 },
  { name: "Richarlison", nameKo: "히샬리송", nationality: "브라질", team: "토트넘", position: "ST", birthYear: 1997, number: 9 },
  { name: "James Maddison", nameKo: "제임스 매디슨", nationality: "잉글랜드", team: "토트넘", position: "CAM", birthYear: 1996, number: 10 },
  { name: "Mathys Tel", nameKo: "마티스 텔", nationality: "프랑스", team: "토트넘", position: "ST", birthYear: 2005, number: 11 },
  { name: "Destiny Udogie", nameKo: "데스티니 우도기", nationality: "이탈리아", team: "토트넘", position: "LB", birthYear: 2002, number: 13 },
  { name: "Archie Gray", nameKo: "아치 그레이", nationality: "잉글랜드", team: "토트넘", position: "RB", birthYear: 2006, number: 14 },
  { name: "Lucas Bergvall", nameKo: "루카스 베리발", nationality: "스웨덴", team: "토트넘", position: "CM", birthYear: 2006, number: 15 },
  { name: "Cristian Romero", nameKo: "크리스티안 로메로", nationality: "아르헨티나", team: "토트넘", position: "CB", birthYear: 1998, number: 17 },
  { name: "Dominic Solanke", nameKo: "도미닉 솔랑케", nationality: "잉글랜드", team: "토트넘", position: "ST", birthYear: 1997, number: 19 },
  { name: "Mohammed Kudus", nameKo: "모하메드 쿠두스", nationality: "가나", team: "토트넘", position: "RW", birthYear: 2000, number: 20 },
  { name: "Dejan Kulusevski", nameKo: "데얀 쿨루셉스키", nationality: "스웨덴", team: "토트넘", position: "RW", birthYear: 2000, number: 21 },
  { name: "Pedro Porro", nameKo: "페드로 포로", nationality: "스페인", team: "토트넘", position: "RB", birthYear: 1999, number: 23 },
  { name: "Djed Spence", nameKo: "제드 스펜스", nationality: "잉글랜드", team: "토트넘", position: "RB", birthYear: 2000, number: 24 },
  { name: "Wilson Odobert", nameKo: "윌슨 오도베르", nationality: "프랑스", team: "토트넘", position: "RW", birthYear: 2004, number: 28 },
  { name: "Pape Matar Sarr", nameKo: "파페 마타르 사르", nationality: "세네갈", team: "토트넘", position: "CM", birthYear: 2002, number: 29 },
  { name: "Rodrigo Bentancur", nameKo: "로드리고 벤탄쿠르", nationality: "우루과이", team: "토트넘", position: "CDM", birthYear: 1997, number: 30 },
  { name: "Marcin Bułka", nameKo: "마르친 부우카", nationality: "폴란드", team: "토트넘", position: "GK", birthYear: 1999, number: 31 },
  { name: "Ben Davies", nameKo: "벤 데이비스", nationality: "웨일스", team: "토트넘", position: "CB", birthYear: 1993, number: 33 },
  { name: "Micky van de Ven", nameKo: "미키 판더펜", nationality: "네덜란드", team: "토트넘", position: "CB", birthYear: 2001, number: 37 },
  { name: "Randal Kolo Muani", nameKo: "란달 콜로 무아니", nationality: "프랑스", team: "토트넘", position: "ST", birthYear: 1998, number: 39 },
  { name: "Brandon Austin", nameKo: "브랜든 오스틴", nationality: "잉글랜드", team: "토트넘", position: "GK", birthYear: 1999, number: 40 },
  { name: "Dane Scarlett", nameKo: "데인 스칼렛", nationality: "잉글랜드", team: "토트넘", position: "ST", birthYear: 2004, number: 44 },

  // 뉴캐슬 (Newcastle United)
  { name: "Nick Pope", nameKo: "닉 포프", nationality: "잉글랜드", team: "뉴캐슬", position: "GK", birthYear: 1992, number: 1 },
  { name: "Kieran Trippier", nameKo: "키어런 트리피어", nationality: "잉글랜드", team: "뉴캐슬", position: "RB", birthYear: 1990, number: 2 },
  { name: "Lewis Hall", nameKo: "루이스 홀", nationality: "잉글랜드", team: "뉴캐슬", position: "LB", birthYear: 2004, number: 3 },
  { name: "Sven Botman", nameKo: "스벤 보트만", nationality: "네덜란드", team: "뉴캐슬", position: "CB", birthYear: 2000, number: 4 },
  { name: "Fabian Schär", nameKo: "파비안 셰어", nationality: "스위스", team: "뉴캐슬", position: "CB", birthYear: 1991, number: 5 },
  { name: "Jamaal Lascelles", nameKo: "자말 라셀스", nationality: "잉글랜드", team: "뉴캐슬", position: "CB", birthYear: 1993, number: 6 },
  { name: "Joelinton", nameKo: "조엘린통", nationality: "브라질", team: "뉴캐슬", position: "CM", birthYear: 1996, number: 7 },
  { name: "Sandro Tonali", nameKo: "산드로 토날리", nationality: "이탈리아", team: "뉴캐슬", position: "CM", birthYear: 2000, number: 8 },
  { name: "Yoane Wissa", nameKo: "요안 위사", nationality: "콩고민주공화국", team: "뉴캐슬", position: "ST", birthYear: 1996, number: 9 },
  { name: "Anthony Gordon", nameKo: "앤서니 고든", nationality: "잉글랜드", team: "뉴캐슬", position: "LW", birthYear: 2001, number: 10 },
  { name: "Harvey Barnes", nameKo: "하비 반스", nationality: "잉글랜드", team: "뉴캐슬", position: "LW", birthYear: 1997, number: 11 },
  { name: "Malick Thiaw", nameKo: "말리크 치아우", nationality: "독일", team: "뉴캐슬", position: "CB", birthYear: 2001, number: 12 },
  { name: "Emil Krafth", nameKo: "에밀 크라프트", nationality: "스웨덴", team: "뉴캐슬", position: "RB", birthYear: 1994, number: 17 },
  { name: "William Osula", nameKo: "윌리엄 오술라", nationality: "덴마크", team: "뉴캐슬", position: "ST", birthYear: 2003, number: 18 },
  { name: "Anthony Elanga", nameKo: "안토니 엘랑가", nationality: "스웨덴", team: "뉴캐슬", position: "RW", birthYear: 2002, number: 20 },
  { name: "Tino Livramento", nameKo: "티노 리브라멘토", nationality: "잉글랜드", team: "뉴캐슬", position: "RB", birthYear: 2002, number: 21 },
  { name: "Jacob Murphy", nameKo: "제이콥 머피", nationality: "잉글랜드", team: "뉴캐슬", position: "RW", birthYear: 1995, number: 23 },
  { name: "John Ruddy", nameKo: "존 러디", nationality: "잉글랜드", team: "뉴캐슬", position: "GK", birthYear: 1986, number: 26 },
  { name: "Nick Woltemade", nameKo: "닉 볼테마데", nationality: "독일", team: "뉴캐슬", position: "ST", birthYear: 2002, number: 27 },
  { name: "Joe Willock", nameKo: "조 윌록", nationality: "잉글랜드", team: "뉴캐슬", position: "CM", birthYear: 1999, number: 28 },
  { name: "Mark Gillespie", nameKo: "마크 길레스피", nationality: "잉글랜드", team: "뉴캐슬", position: "GK", birthYear: 1992, number: 29 },
  { name: "Harrison Ashby", nameKo: "해리슨 애슈비", nationality: "스코틀랜드", team: "뉴캐슬", position: "RB", birthYear: 2001, number: 30 },
  { name: "Aaron Ramsdale", nameKo: "아론 램스데일", nationality: "잉글랜드", team: "뉴캐슬", position: "GK", birthYear: 1998, number: 32 },
  { name: "Dan Burn", nameKo: "댄 번", nationality: "잉글랜드", team: "뉴캐슬", position: "CB", birthYear: 1992, number: 33 },
  { name: "Alex Murphy", nameKo: "알렉스 머피", nationality: "아일랜드", team: "뉴캐슬", position: "CB", birthYear: 2004, number: 37 },
  { name: "Bruno Guimarães", nameKo: "브루누 기마랑이스", nationality: "브라질", team: "뉴캐슬", position: "CM", birthYear: 1997, number: 39 },
  { name: "Jacob Ramsey", nameKo: "제이콥 램지", nationality: "잉글랜드", team: "뉴캐슬", position: "CM", birthYear: 2001, number: 41 },
  { name: "Lewis Miley", nameKo: "루이스 마일리", nationality: "잉글랜드", team: "뉴캐슬", position: "CM", birthYear: 2006, number: 67 },

    // 아스톤 빌라
    // 아스톤 빌라 FC 2025-26 시즌 스쿼드 명단
{ name: "Matty Cash", nameKo: "매티 캐시", nationality: "폴란드", team: "아스톤 빌라", position: "DF", birthYear: 1997, number: 2 },
{ name: "Victor Lindelöf", nameKo: "빅토르 린델뢰프", nationality: "스웨덴", team: "아스톤 빌라", position: "DF", birthYear: 1994, number: 3 },
{ name: "Ezri Konsa", nameKo: "에즈리 콘사", nationality: "잉글랜드", team: "아스톤 빌라", position: "DF", birthYear: 1997, number: 4 },
{ name: "Tyrone Mings", nameKo: "타이론 밍스", nationality: "잉글랜드", team: "아스톤 빌라", position: "DF", birthYear: 1993, number: 5 },
{ name: "Ross Barkley", nameKo: "로스 바클리", nationality: "잉글랜드", team: "아스톤 빌라", position: "MF", birthYear: 1993, number: 6 },
{ name: "John McGinn", nameKo: "존 맥긴", nationality: "스코틀랜드", team: "아스톤 빌라", position: "MF", birthYear: 1994, number: 7 },
{ name: "Youri Tielemans", nameKo: "유리 틸레만스", nationality: "벨기에", team: "아스톤 빌라", position: "MF", birthYear: 1997, number: 8 },
{ name: "Harvey Elliott", nameKo: "하비 엘리엇", nationality: "잉글랜드", team: "아스톤 빌라", position: "MF", birthYear: 2003, number: 9 },
{ name: "Emiliano Buendía", nameKo: "에밀리아노 부엔디아", nationality: "아르헨티나", team: "아스톤 빌라", position: "MF", birthYear: 1996, number: 10 },
{ name: "Ollie Watkins", nameKo: "올리 왓킨스", nationality: "잉글랜드", team: "아스톤 빌라", position: "FW", birthYear: 1995, number: 11 },
{ name: "Lucas Digne", nameKo: "뤼카 디뉴", nationality: "프랑스", team: "아스톤 빌라", position: "DF", birthYear: 1993, number: 12 },
{ name: "Pau Torres", nameKo: "파우 토레스", nationality: "스페인", team: "아스톤 빌라", position: "DF", birthYear: 1997, number: 14 },
{ name: "Andrés García", nameKo: "안드레스 가르시아", nationality: "스페인", team: "아스톤 빌라", position: "DF", birthYear: 2003, number: 16 },
{ name: "Donyell Malen", nameKo: "도니얼 말런", nationality: "네덜란드", team: "아스톤 빌라", position: "FW", birthYear: 1999, number: 17 },
{ name: "Jadon Sancho", nameKo: "제이든 산초", nationality: "잉글랜드", team: "아스톤 빌라", position: "FW", birthYear: 2000, number: 19 },
{ name: "Ian Maatsen", nameKo: "이안 마트센", nationality: "네덜란드", team: "아스톤 빌라", position: "DF", birthYear: 2002, number: 22 },
{ name: "Emiliano Martínez", nameKo: "에밀리아노 마르티네스", nationality: "아르헨티나", team: "아스톤 빌라", position: "GK", birthYear: 1992, number: 23 },
{ name: "Amadou Onana", nameKo: "아마두 오나나", nationality: "벨기에", team: "아스톤 빌라", position: "MF", birthYear: 2001, number: 24 },
{ name: "Lamare Bogarde", nameKo: "라마레 보가드", nationality: "네덜란드", team: "아스톤 빌라", position: "MF", birthYear: 2004, number: 26 },
{ name: "Morgan Rogers", nameKo: "모건 로저스", nationality: "잉글랜드", team: "아스톤 빌라", position: "FW", birthYear: 2002, number: 27 },
{ name: "Evann Guessand", nameKo: "에반 게상", nationality: "코트디부아르", team: "아스톤 빌라", position: "FW", birthYear: 2001, number: 29 },
{ name: "Marco Bizot", nameKo: "마르코 비조트", nationality: "네덜란드", team: "아스톤 빌라", position: "GK", birthYear: 1991, number: 40 },
{ name: "Boubacar Kamara", nameKo: "부바카르 카마라", nationality: "프랑스", team: "아스톤 빌라", position: "MF", birthYear: 1999, number: 44 },
{ name: "Alysson Edward", nameKo: "알리송 에두아르드", nationality: "브라질", team: "아스톤 빌라", position: "FW", birthYear: 2006, number: 47 },
    // 선덜랜드
    // 선덜랜드 AFC 2025-26 시즌 전체 스쿼드 명단
    { name: "Anthony Patterson", nameKo: "앤서니 패터슨", nationality: "잉글랜드", team: "선덜랜드", position: "GK", birthYear: 2000, number: 1 },
    { name: "Dennis Cirkin", nameKo: "데니스 서킨", nationality: "잉글랜드", team: "선덜랜드", position: "LB", birthYear: 2002, number: 3 },
    { name: "Dan Neil", nameKo: "댄 닐", nationality: "잉글랜드", team: "선덜랜드", position: "CM", birthYear: 2001, number: 4 },
    { name: "Daniel Ballard", nameKo: "대니얼 발라드", nationality: "북아일랜드", team: "선덜랜드", position: "CB", birthYear: 1999, number: 5 },
    { name: "Lutsharel Geertruida", nameKo: "루츠하럴 헤이르트라위다", nationality: "네덜란드", team: "선덜랜드", position: "RB", birthYear: 2000, number: 6 },
    { name: "Montassir Lahtimi", nameKo: "몬타세르 탈비", nationality: "모로코", team: "선덜랜드", position: "RW", birthYear: 2001, number: 7 },
    { name: "Brian Brobbey", nameKo: "브라이언 브로비", nationality: "네덜란드", team: "선덜랜드", position: "ST", birthYear: 2002, number: 9 },
    { name: "Chris Rigg", nameKo: "크리스 리그", nationality: "잉글랜드", team: "선덜랜드", position: "CM", birthYear: 2007, number: 11 },
    { name: "Timothée Mayanda", nameKo: "티모테 마엔다", nationality: "프랑스", team: "선덜랜드", position: "LB", birthYear: 2006, number: 12 },
    { name: "Luke O'Nien", nameKo: "루크 오나인", nationality: "잉글랜드", team: "선덜랜드", position: "CB", birthYear: 1994, number: 13 },
    { name: "Niall Huggins", nameKo: "나이얼 먼들", nationality: "웨일스", team: "선덜랜드", position: "RB", birthYear: 2000, number: 14 },
    { name: "Omar Alderete", nameKo: "오마르 알데레테", nationality: "파라과이", team: "선덜랜드", position: "CB", birthYear: 1996, number: 15 },
    { name: "Euna Nuku", nameKo: "은나 누쿠", nationality: "뉴질랜드", team: "선덜랜드", position: "CB", birthYear: 2006, number: 16 },
    { name: "Reinildo Mandava", nameKo: "헤이닐두 만다바", nationality: "모잠비크", team: "선덜랜드", position: "LB", birthYear: 1994, number: 17 },
    { name: "Wilson Isidor", nameKo: "윌슨 이지도르", nationality: "프랑스", team: "선덜랜드", position: "ST", birthYear: 2000, number: 18 },
    { name: "Ibrahim Diarra", nameKo: "이브라힘 디아라", nationality: "말리", team: "선덜랜드", position: "RW", birthYear: 2006, number: 19 },
    { name: "Nordi Mukiele", nameKo: "노르디 무키엘레", nationality: "프랑스", team: "선덜랜드", position: "RB", birthYear: 1997, number: 20 },
    { name: "Deano Moore", nameKo: "디노 무어", nationality: "잉글랜드", team: "선덜랜드", position: "GK", birthYear: 2006, number: 21 },
    { name: "Robin Roefs", nameKo: "로빈 루프스", nationality: "네덜란드", team: "선덜랜드", position: "GK", birthYear: 2003, number: 22 },
    { name: "Simon Adingra", nameKo: "시몽 아딩그라", nationality: "코트디부아르", team: "선덜랜드", position: "LW", birthYear: 2002, number: 24 },
    { name: "Hamed Traorè", nameKo: "하메드 트라오레", nationality: "코트디부아르", team: "선덜랜드", position: "CAM", birthYear: 2000, number: 25 },
    { name: "Arthur Masuaku", nameKo: "아르튀르 마슈아퀴", nationality: "콩고민주공화국", team: "선덜랜드", position: "LB", birthYear: 1993, number: 26 },
    { name: "Noah Sadiki", nameKo: "노아 사디키", nationality: "벨기에", team: "선덜랜드", position: "CDM", birthYear: 2004, number: 27 },
    { name: "Enzo Le Fée", nameKo: "엔초 르 페", nationality: "프랑스", team: "선덜랜드", position: "CM", birthYear: 2000, number: 28 },
    { name: "Abdoullah Ba", nameKo: "압둘라히 바", nationality: "프랑스", team: "선덜랜드", position: "RW", birthYear: 2003, number: 29 },
    { name: "Trai Hume", nameKo: "트라이 휴엄", nationality: "북아일랜드", team: "선덜랜드", position: "RB", birthYear: 2002, number: 32 },
    { name: "Jodel Dossou", nameKo: "요델 도수", nationality: "베냉", team: "선덜랜드", position: "RW", birthYear: 1992, number: 33 },
    { name: "Granit Xhaka", nameKo: "그라니트 자카", nationality: "스위스", team: "선덜랜드", position: "CDM", birthYear: 1992, number: 34 },
    { name: "Timothée Pembélé", nameKo: "티모테 펨벨레", nationality: "프랑스", team: "선덜랜드", position: "RB", birthYear: 2002, number: 40 },
    { name: "Tommy Watson", nameKo: "토미 존슨", nationality: "잉글랜드", team: "선덜랜드", position: "LW", birthYear: 2006, number: 41 },
    { name: "Adil Aouchiche", nameKo: "아딜 아우시슈", nationality: "프랑스", team: "선덜랜드", position: "CAM", birthYear: 2002, number: 42 },
    { name: "Joe Anderson", nameKo: "조 앤더슨", nationality: "잉글랜드", team: "선덜랜드", position: "CB", birthYear: 2001, number: 45 },
    { name: "El Hadji Ba", nameKo: "엘 하지 바", nationality: "모리타니", team: "선덜랜드", position: "CM", birthYear: 1993, number: 46 },
    { name: "Ian Poveda", nameKo: "이안 포베다", nationality: "콜롬비아", team: "선덜랜드", position: "RW", birthYear: 2000, number: 49 },
    { name: "Zidan Sertdemir", nameKo: "지단 세르트데미르", nationality: "덴마크", team: "선덜랜드", position: "CM", birthYear: 2005, number: 50 },
    // 브라이튼
    // 브라이튼 앤 호브 알비온 2025-26 시즌 스쿼드 (이미지 대조 완료)
{ name: "Bart Verbruggen", nameKo: "바르트 페르브뤼헨", nationality: "네덜란드", team: "브라이튼", position: "GK", birthYear: 2002, number: 1 },
{ name: "Adam Webster", nameKo: "아담 웹스터", nationality: "잉글랜드", team: "브라이튼", position: "CB", birthYear: 1995, number: 4 },
{ name: "Lewis Dunk", nameKo: "루이스 덩크", nationality: "잉글랜드", team: "브라이튼", position: "CB", birthYear: 1991, number: 5 },
{ name: "Jan Paul van Hecke", nameKo: "얀 폴 반 헤케", nationality: "네덜란드", team: "브라이튼", position: "CB", birthYear: 2000, number: 6 },
{ name: "Solly March", nameKo: "솔리 마치", nationality: "잉글랜드", team: "브라이튼", position: "RW", birthYear: 1994, number: 7 },
{ name: "Brajan Gruda", nameKo: "브라얀 그루다", nationality: "독일", team: "브라이튼", position: "RW", birthYear: 2004, number: 8 },
{ name: "Stefanos Tzimas", nameKo: "스테파노스 치마스", nationality: "그리스", team: "브라이튼", position: "ST", birthYear: 2006, number: 9 },
{ name: "Georginio Rutter", nameKo: "조르지니오 뤼터", nationality: "프랑스", team: "브라이튼", position: "ST", birthYear: 2002, number: 10 },
{ name: "Yankuba Minteh", nameKo: "얀쿠바 민테", nationality: "감비아", team: "브라이튼", position: "RW", birthYear: 2004, number: 11 },
{ name: "Jack Hinshelwood", nameKo: "잭 힌셜우드", nationality: "잉글랜드", team: "브라이튼", position: "RB", birthYear: 2005, number: 13 },
{ name: "Tommy Watson", nameKo: "토미 왓슨", nationality: "잉글랜드", team: "브라이튼", position: "LW", birthYear: 2006, number: 14 },
{ name: "Carlos Baleba", nameKo: "카를로스 발레바", nationality: "카메룬", team: "브라이튼", position: "CDM", birthYear: 2004, number: 17 },
{ name: "Danny Welbeck", nameKo: "대니 웰백", nationality: "잉글랜드", team: "브라이튼", position: "ST", birthYear: 1990, number: 18 },
{ name: "Charalampos Kostoulas", nameKo: "하라람포스 코스툴라스", nationality: "그리스", team: "브라이튼", position: "ST", birthYear: 2007, number: 19 },
{ name: "James Milner", nameKo: "제임스 밀너", nationality: "잉글랜드", team: "브라이튼", position: "CM", birthYear: 1986, number: 20 },
{ name: "Olivier Boscagli", nameKo: "올리비에 보스카글리", nationality: "프랑스", team: "브라이튼", position: "CB", birthYear: 1997, number: 21 },
{ name: "Kaoru Mitoma", nameKo: "미토마 카오루", nationality: "일본", team: "브라이튼", position: "LW", birthYear: 1997, number: 22 },
{ name: "Jason Steele", nameKo: "제이슨 스틸", nationality: "잉글랜드", team: "브라이튼", position: "GK", birthYear: 1990, number: 23 },
{ name: "Ferdi Kadıoğlu", nameKo: "페르디 카디올루", nationality: "터키", team: "브라이튼", position: "LB", birthYear: 1999, number: 24 },
{ name: "Diego Gómez", nameKo: "디에고 고메스", nationality: "파라과이", team: "브라이튼", position: "CM", birthYear: 2003, number: 25 },
{ name: "Yasin Ayari", nameKo: "야신 아야리", nationality: "스웨덴", team: "브라이튼", position: "CM", birthYear: 2003, number: 26 },
{ name: "Mats Wieffer", nameKo: "마츠 비퍼", nationality: "네덜란드", team: "브라이튼", position: "CDM", birthYear: 1999, number: 27 },
{ name: "Maxim De Cuyper", nameKo: "막심 더 카위퍼르", nationality: "벨기에", team: "브라이튼", position: "LB", birthYear: 2000, number: 29 },
{ name: "Pascal Groß", nameKo: "파스칼 그로스", nationality: "독일", team: "브라이튼", position: "CM", birthYear: 1991, number: 30 },
{ name: "Joël Veltman", nameKo: "조엘 벨트만", nationality: "네덜란드", team: "브라이튼", position: "RB", birthYear: 1992, number: 34 },
{ name: "Tom McGill", nameKo: "톰 맥길", nationality: "캐나다", team: "브라이튼", position: "GK", birthYear: 2000, number: 38 },
{ name: "Diego Coppola", nameKo: "디에고 코폴라", nationality: "이탈리아", team: "브라이튼", position: "CB", birthYear: 2003, number: 42 },
    // 울버햄튼
    // 울버햄튼 원더러스 FC 2025-26 시즌 스쿼드 명단 (이미지 기준)
{ name: "José Sá", nameKo: "주제 사", nationality: "포르투갈", team: "울버햄튼", position: "GK", birthYear: 1993, number: 1 },
{ name: "Matt Doherty", nameKo: "맷 도허티", nationality: "아일랜드", team: "울버햄튼", position: "DF", birthYear: 1992, number: 2 },
{ name: "Hugo Bueno", nameKo: "우고 부에노", nationality: "스페인", team: "울버햄튼", position: "DF", birthYear: 2002, number: 3 },
{ name: "Santiago Bueno", nameKo: "산티아고 부에노", nationality: "우루과이", team: "울버햄튼", position: "DF", birthYear: 1998, number: 4 },
{ name: "Marshall Munetsi", nameKo: "마샬 무네치", nationality: "짐바브웨", team: "울버햄튼", position: "MF", birthYear: 1996, number: 5 },
{ name: "Boubacar Olpe", nameKo: "부바카르 올페", nationality: "프랑스", team: "울버햄튼", position: "MF", birthYear: 2002, number: 6 },
{ name: "André", nameKo: "안드레", nationality: "브라질", team: "울버햄튼", position: "MF", birthYear: 2001, number: 7 },
{ name: "João Gomes", nameKo: "주앙 고메스", nationality: "브라질", team: "울버햄튼", position: "MF", birthYear: 2001, number: 8 },
{ name: "Jørgen Strand Larsen", nameKo: "예르겐 스트란 라르센", nationality: "노르웨이", team: "울버햄튼", position: "FW", birthYear: 2000, number: 9 },
{ name: "Jhon Arias", nameKo: "존 아리아스", nationality: "콜롬비아", team: "울버햄튼", position: "FW", birthYear: 1997, number: 10 },
{ name: "Hwang Hee-Chan", nameKo: "황희찬", nationality: "대한민국", team: "울버햄튼", position: "FW", birthYear: 1996, number: 11 },
{ name: "Emmanuel Agbadu", nameKo: "에마뉘엘 아그바두", nationality: "코트디부아르", team: "울버햄튼", position: "DF", birthYear: 1997, number: 12 },
{ name: "Tolu Arokodare", nameKo: "톨루 아로코다레", nationality: "나이지리아", team: "울버햄튼", position: "FW", birthYear: 2000, number: 14 },
{ name: "Yerson Mosquera", nameKo: "예르손 모스케라", nationality: "콜롬비아", team: "울버햄튼", position: "DF", birthYear: 2001, number: 15 },
{ name: "Pedro Lima", nameKo: "페드루 리마", nationality: "브라질", team: "울버햄튼", position: "DF", birthYear: 2006, number: 17 },
{ name: "Rodrigo Gomes", nameKo: "로드리구 고메스", nationality: "포르투갈", team: "울버햄튼", position: "MF", birthYear: 2003, number: 21 },
{ name: "Chiquinho", nameKo: "치키뉴", nationality: "포르투갈", team: "울버햄튼", position: "FW", birthYear: 2000, number: 23 },
{ name: "Toti Gomes", nameKo: "토티 고메스", nationality: "포르투갈", team: "울버햄튼", position: "DF", birthYear: 1999, number: 24 },
{ name: "Dan Bentley", nameKo: "댄 벤틀리", nationality: "잉글랜드", team: "울버햄튼", position: "GK", birthYear: 1993, number: 25 },
{ name: "Jean-Ricner Bellegarde", nameKo: "장리크네 벨가르드", nationality: "프랑스", team: "울버햄튼", position: "MF", birthYear: 1998, number: 27 },
{ name: "Pere Lopes", nameKo: "페레 로페스", nationality: "포르투갈", team: "울버햄튼", position: "GK", birthYear: 1999, number: 28 },
{ name: "Enso González", nameKo: "엔소 곤살레스", nationality: "파라과이", team: "울버햄튼", position: "FW", birthYear: 2005, number: 30 },
{ name: "Sam Johnstone", nameKo: "샘 존스톤", nationality: "잉글랜드", team: "울버햄튼", position: "GK", birthYear: 1993, number: 31 },
{ name: "Ousmane Mane", nameKo: "우스만 마네", nationality: "세네갈", team: "울버햄튼", position: "FW", birthYear: 2006, number: 36 },
{ name: "Tommy Doyle", nameKo: "토미 도일", nationality: "잉글랜드", team: "울버햄튼", position: "MF", birthYear: 2001, number: 37 },
{ name: "Jackson Tchatchoua", nameKo: "잭슨 차추아", nationality: "카메룬", team: "울버햄튼", position: "DF", birthYear: 2001, number: 38 },
    // 크리스탈 팰리스
    // 크리스탈 팰리스 FC 2025-26 시즌 스쿼드 명단 (이미지 기준)
{ name: "Dean Henderson", nameKo: "딘 헨더슨", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "GK", birthYear: 1997, number: 1 },
{ name: "Daniel Muñoz", nameKo: "다니엘 무뇨스", nationality: "콜롬비아", team: "크리스탈 팰리스", position: "DF", birthYear: 1996, number: 2 },
{ name: "Tyrick Mitchell", nameKo: "타이릭 미첼", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "DF", birthYear: 1999, number: 3 },
{ name: "Maxence Lacroix", nameKo: "막상스 라크루아", nationality: "프랑스", team: "크리스탈 팰리스", position: "DF", birthYear: 2000, number: 5 },
{ name: "Marc Guéhi", nameKo: "마크 게히", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "DF", birthYear: 2000, number: 6 },
{ name: "Ismaïla Sarr", nameKo: "이스마일라 사르", nationality: "세네갈", team: "크리스탈 팰리스", position: "FW", birthYear: 1998, number: 7 },
{ name: "Jefferson Lerma", nameKo: "제페르손 레르마", nationality: "콜롬비아", team: "크리스탈 팰리스", position: "MF", birthYear: 1994, number: 8 },
{ name: "Eddie Nketiah", nameKo: "에디 은케티아", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "FW", birthYear: 1999, number: 9 },
{ name: "Yeremy Pino", nameKo: "예레미 피노", nationality: "스페인", team: "크리스탈 팰리스", position: "FW", birthYear: 2002, number: 10 },
{ name: "Matheus França", nameKo: "마테우스 프랑사", nationality: "브라질", team: "크리스탈 팰리스", position: "MF", birthYear: 2004, number: 11 },
{ name: "Uchechi Chansly", nameKo: "우체치 찬슬리", nationality: "나이지리아", team: "크리스탈 팰리스", position: "FW", birthYear: 2005, number: 12 },
{ name: "Jean-Philippe Mateta", nameKo: "장필리프 마테타", nationality: "프랑스", team: "크리스탈 팰리스", position: "FW", birthYear: 1997, number: 14 },
{ name: "Nathaniel Clyne", nameKo: "나다니엘 클라인", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "DF", birthYear: 1991, number: 17 },
{ name: "Daichi Kamada", nameKo: "카마다 다이치", nationality: "일본", team: "크리스탈 팰리스", position: "MF", birthYear: 1996, number: 18 },
{ name: "Will Hughes", nameKo: "윌 휴즈", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "MF", birthYear: 1995, number: 19 },
{ name: "Adam Wharton", nameKo: "애덤 워튼", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "MF", birthYear: 2004, number: 20 },
{ name: "Caleb Kango", nameKo: "케일럽 캉고", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "FW", birthYear: 2006, number: 23 },
{ name: "Borna Sosa", nameKo: "보르나 소사", nationality: "크로아티아", team: "크리스탈 팰리스", position: "DF", birthYear: 1998, number: 24 },
{ name: "Chris Richards", nameKo: "크리스 리차즈", nationality: "미국", team: "크리스탈 팰리스", position: "DF", birthYear: 2000, number: 26 },
{ name: "Cheick Doucouré", nameKo: "셰이크 두쿠레", nationality: "말리", team: "크리스탈 팰리스", position: "MF", birthYear: 2000, number: 28 },
{ name: "Remi Matthews", nameKo: "레미 매튜스", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "GK", birthYear: 1994, number: 31 },
{ name: "Chadi Riad", nameKo: "샤디 리아드", nationality: "모로코", team: "크리스탈 팰리스", position: "DF", birthYear: 2003, number: 34 },
{ name: "Franco Kropflha", nameKo: "프랑코 크로포르하", nationality: "오스트리아", team: "크리스탈 팰리스", position: "DF", birthYear: 2005, number: 38 },
{ name: "Rodney Akabosi", nameKo: "로드니 아카보시", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "DF", birthYear: 2005, number: 42 },
{ name: "Franco Benitez", nameKo: "프랑코 베니테스", nationality: "아르헨티나", team: "크리스탈 팰리스", position: "GK", birthYear: 2006, number: 44 },
{ name: "Devanny", nameKo: "데버니", nationality: "프랑스", team: "크리스탈 팰리스", position: "DF", birthYear: 2004, number: 55 },
{ name: "Cardines", nameKo: "카딘스", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "DF", birthYear: 2005, number: 59 },
{ name: "Mustapha", nameKo: "무스타파", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "FW", birthYear: 2006, number: 0 },
    // 에버튼
    // 에버튼 FC 2025-26 시즌 스쿼드 명단 (이미지 기준)
{ name: "Jordan Pickford", nameKo: "조던 픽포드", nationality: "잉글랜드", team: "에버튼", position: "GK", birthYear: 1994, number: 1 },
{ name: "Nathan Patterson", nameKo: "네이선 패터슨", nationality: "스코틀랜드", team: "에버튼", position: "DF", birthYear: 2001, number: 2 },
{ name: "Michael Keane", nameKo: "마이클 킨", nationality: "잉글랜드", team: "에버튼", position: "DF", birthYear: 1993, number: 5 },
{ name: "James Tarkowski", nameKo: "제임스 타코우스키", nationality: "잉글랜드", team: "에버튼", position: "DF", birthYear: 1992, number: 6 },
{ name: "Dwight McNeil", nameKo: "드와이트 맥닐", nationality: "잉글랜드", team: "에버튼", position: "MF", birthYear: 1999, number: 7 },
{ name: "Beto", nameKo: "베투", nationality: "포르투갈", team: "에버튼", position: "FW", birthYear: 1998, number: 9 },
{ name: "Iliman Ndiaye", nameKo: "일리만 은디아예", nationality: "세네갈", team: "에버튼", position: "FW", birthYear: 2000, number: 10 },
{ name: "Abdoulaye Doucouré", nameKo: "압둘라예 두쿠레", nationality: "말리", team: "에버튼", position: "MF", birthYear: 1993, number: 11 },
{ name: "Mark Travers", nameKo: "마크 트래버스", nationality: "아일랜드", team: "에버튼", position: "GK", birthYear: 1999, number: 12 },
{ name: "Jake O'Brien", nameKo: "제이크 오브라이언", nationality: "아일랜드", team: "에버튼", position: "DF", birthYear: 2001, number: 15 },
{ name: "Vitaliy Mykolenko", nameKo: "비탈리 미콜렌코", nationality: "우크라이나", team: "에버튼", position: "DF", birthYear: 1999, number: 16 },
{ name: "Jack Grealish", nameKo: "잭 그릴리쉬", nationality: "잉글랜드", team: "에버튼", position: "MF", birthYear: 1995, number: 18 },
{ name: "Tyler Dibling", nameKo: "타일러 디블링", nationality: "잉글랜드", team: "에버튼", position: "MF", birthYear: 2006, number: 20 },
{ name: "Kiernan Dewsbury-Hall", nameKo: "키어넌 듀스버리홀", nationality: "잉글랜드", team: "에버튼", position: "MF", birthYear: 1998, number: 22 },
{ name: "Séamus Coleman", nameKo: "셰이머스 콜먼", nationality: "아일랜드", team: "에버튼", position: "DF", birthYear: 1988, number: 23 },
{ name: "Carlos Alcaraz", nameKo: "카를로스 알카라스", nationality: "아르헨티나", team: "에버튼", position: "MF", birthYear: 2002, number: 24 },
{ name: "Idrissa Gueye", nameKo: "이드리사 게예", nationality: "세네갈", team: "에버튼", position: "MF", birthYear: 1989, number: 27 },
{ name: "Thomas King", nameKo: "토마스 킹", nationality: "웨일스", team: "에버튼", position: "GK", birthYear: 2006, number: 31 },
{ name: "Jarrad Branthwaite", nameKo: "재러드 브랜스웨이트", nationality: "잉글랜드", team: "에버튼", position: "DF", birthYear: 2002, number: 32 },
{ name: "Nathan Roel", nameKo: "네이선 뢸", nationality: "잉글랜드", team: "에버튼", position: "DF", birthYear: 2005, number: 34 },
{ name: "James Garner", nameKo: "제임스 가너", nationality: "잉글랜드", team: "에버튼", position: "MF", birthYear: 2001, number: 37 },
{ name: "Tyler Morton", nameKo: "타일러 모튼", nationality: "잉글랜드", team: "에버튼", position: "MF", birthYear: 2002, number: 38 },
{ name: "Adam Aznou", nameKo: "아담 아즈누", nationality: "모로코", team: "에버튼", position: "DF", birthYear: 2006, number: 39 },
{ name: "Tim Iroegbunam", nameKo: "팀 이로에구부남", nationality: "잉글랜드", team: "에버튼", position: "MF", birthYear: 2003, number: 42 },
{ name: "Kieran Armstrong", nameKo: "키어런 암스트롱", nationality: "잉글랜드", team: "에버튼", position: "FW", birthYear: 2005, number: 45 },
    // 풀럼
    // 풀럼 FC 2025-26 시즌 스쿼드 명단 (이미지 기준)
{ name: "Bernd Leno", nameKo: "베른트 레노", nationality: "독일", team: "풀럼", position: "GK", birthYear: 1992, number: 1 },
{ name: "Kenny Tete", nameKo: "케니 테테", nationality: "네덜란드", team: "풀럼", position: "DF", birthYear: 1995, number: 2 },
{ name: "Calvin Bassey", nameKo: "캘빈 배시", nationality: "나이지리아", team: "풀럼", position: "DF", birthYear: 1999, number: 3 },
{ name: "Joachim Andersen", nameKo: "요아킴 안데르센", nationality: "덴마크", team: "풀럼", position: "DF", birthYear: 1996, number: 5 },
{ name: "Harrison Reed", nameKo: "해리슨 리드", nationality: "잉글랜드", team: "풀럼", position: "MF", birthYear: 1995, number: 6 },
{ name: "Raúl Jiménez", nameKo: "라울 히메네스", nationality: "멕시코", team: "풀럼", position: "FW", birthYear: 1991, number: 7 },
{ name: "Harry Wilson", nameKo: "해리 윌슨", nationality: "웨일스", team: "풀럼", position: "MF", birthYear: 1997, number: 8 },
{ name: "Rodrigo Muniz", nameKo: "로드리고 무니스", nationality: "브라질", team: "풀럼", position: "FW", birthYear: 2001, number: 9 },
{ name: "Tom Cairney", nameKo: "톰 케어니", nationality: "스코틀랜드", team: "풀럼", position: "MF", birthYear: 1991, number: 10 },
{ name: "Adama Traoré", nameKo: "아다마 트라오레", nationality: "스페인", team: "풀럼", position: "FW", birthYear: 1996, number: 11 },
{ name: "Jorge Cuenca", nameKo: "호르헤 쿠엔카", nationality: "스페인", team: "풀럼", position: "DF", birthYear: 1999, number: 15 },
{ name: "Sander Berge", nameKo: "산데르 베르게", nationality: "노르웨이", team: "풀럼", position: "MF", birthYear: 1998, number: 16 },
{ name: "Alex Iwobi", nameKo: "알렉스 이워비", nationality: "나이지리아", team: "풀럼", position: "MF", birthYear: 1996, number: 17 },
{ name: "Emanuel Koussi-Asare", nameKo: "에마뉘엘 쿠시아사레", nationality: "스웨덴", team: "풀럼", position: "FW", birthYear: 2005, number: 18 },
{ name: "Samuel Chukwueze", nameKo: "사무엘 추쿠에제", nationality: "나이지리아", team: "풀럼", position: "FW", birthYear: 1999, number: 19 },
{ name: "Saša Lukić", nameKo: "사샤 루키치", nationality: "세르비아", team: "풀럼", position: "MF", birthYear: 1996, number: 20 },
{ name: "Timothy Castagne", nameKo: "티모티 카스타뉴", nationality: "벨기에", team: "풀럼", position: "DF", birthYear: 1995, number: 21 },
{ name: "Kevin Mbabu", nameKo: "케빈 음바부", nationality: "스위스", team: "풀럼", position: "DF", birthYear: 1995, number: 22 },
{ name: "Benjamin Lecomte", nameKo: "벤자민 르콩트", nationality: "프랑스", team: "풀럼", position: "GK", birthYear: 1991, number: 23 },
{ name: "Jeff King", nameKo: "제프 킹", nationality: "잉글랜드", team: "풀럼", position: "DF", birthYear: 1995, number: 24 },
{ name: "Ryan Sessegnon", nameKo: "라이언 세세뇽", nationality: "잉글랜드", team: "풀럼", position: "DF", birthYear: 2000, number: 30 },
{ name: "Issa Diop", nameKo: "이사 디오프", nationality: "프랑스", team: "풀럼", position: "DF", birthYear: 1997, number: 31 },
{ name: "Emile Smith Rowe", nameKo: "에밀 스미스 로우", nationality: "잉글랜드", team: "풀럼", position: "MF", birthYear: 2000, number: 32 },
{ name: "Antonee Robinson", nameKo: "안토니 로빈슨", nationality: "미국", team: "풀럼", position: "DF", birthYear: 1997, number: 33 }
  ],
  "라리가": [
    // 레알 마드리드
    { name: "Jude Bellingham", nameKo: "주드 벨링엄", nationality: "잉글랜드", team: "레알 마드리드", position: "CAM", birthYear: 2003, number: 5 },
    { name: "Vinicius Jr", nameKo: "비니시우스 주니어", nationality: "브라질", team: "레알 마드리드", position: "LW", birthYear: 2000, number: 7 },
    { name: "Kylian Mbappe", nameKo: "킬리안 음바페", nationality: "프랑스", team: "레알 마드리드", position: "ST", birthYear: 1998, number: 9 },
    { name: "Federico Valverde", nameKo: "페데리코 발베르데", nationality: "우루과이", team: "레알 마드리드", position: "CM", birthYear: 1998, number: 8 },
    { name: "Thibaut Courtois", nameKo: "티보 쿠르투아", nationality: "벨기에", team: "레알 마드리드", position: "GK", birthYear: 1992, number: 1 },
    { name: "Antonio Rudiger", nameKo: "안토니오 뤼디거", nationality: "독일", team: "레알 마드리드", position: "CB", birthYear: 1993, number: 22 },
    { name: "Rodrygo", nameKo: "호드리구", nationality: "브라질", team: "레알 마드리드", position: "RW", birthYear: 2001, number: 11 },
    { name: "Eduardo Camavinga", nameKo: "에두아르도 카마빙가", nationality: "프랑스", team: "레알 마드리드", position: "CM", birthYear: 2002, number: 12 },
    { name: "Aurelien Tchouameni", nameKo: "오렐리앙 추아메니", nationality: "프랑스", team: "레알 마드리드", position: "CDM", birthYear: 2000, number: 14 },
    { name: "Dani Carvajal", nameKo: "다니 카르바할", nationality: "스페인", team: "레알 마드리드", position: "RB", birthYear: 1992, number: 2 },
    { name: "Ferland Mendy", nameKo: "페를랑 멘디", nationality: "프랑스", team: "레알 마드리드", position: "LB", birthYear: 1995, number: 23 },
    { name: "Eder Militao", nameKo: "에데르 밀리탕", nationality: "브라질", team: "레알 마드리드", position: "CB", birthYear: 1998, number: 3 },
    { name: "David Alaba", nameKo: "다비드 알라바", nationality: "오스트리아", team: "레알 마드리드", position: "CB", birthYear: 1992, number: 4 },
    { name: "Brahim Diaz", nameKo: "브라힘 디아스", nationality: "모로코", team: "레알 마드리드", position: "CAM", birthYear: 1999, number: 21 },
    { name: "Arda Guler", nameKo: "아르다 귈러러", nationality: "터키", team: "레알 마드리드", position: "CAM", birthYear: 2005, number: 15 },
    // 바르셀로나
    { name: "Lamine Yamal", nameKo: "라민 야말", nationality: "스페인", team: "바르셀로나", position: "RW", birthYear: 2007, number: 19 },
    { name: "Pedri", nameKo: "페드리", nationality: "스페인", team: "바르셀로나", position: "CM", birthYear: 2002, number: 8 },
    { name: "Gavi", nameKo: "가비", nationality: "스페인", team: "바르셀로나", position: "CM", birthYear: 2004, number: 6 },
    { name: "Robert Lewandowski", nameKo: "로베르트 레반도프스키", nationality: "폴란드", team: "바르셀로나", position: "ST", birthYear: 1988, number: 9 },
    { name: "Raphinha", nameKo: "하피냐", nationality: "브라질", team: "바르셀로나", position: "RW", birthYear: 1996, number: 11 },
    { name: "Ronald Araujo", nameKo: "로날드 아라우호", nationality: "우루과이", team: "바르셀로나", position: "CB", birthYear: 1999, number: 4 },
    { name: "Marc-Andre ter Stegen", nameKo: "마르크-안드레 테어 슈테겐", nationality: "독일", team: "바르셀로나", position: "GK", birthYear: 1992, number: 1 },
    { name: "Frenkie de Jong", nameKo: "프렝키 더 용", nationality: "네덜란드", team: "바르셀로나", position: "CM", birthYear: 1997, number: 21 },
    { name: "Joao Cancelo", nameKo: "주앙 칸셀루", nationality: "포르투갈", team: "바르셀로나", position: "RB", birthYear: 1994, number: 2 },
    { name: "Jules Kounde", nameKo: "쥘 쿤데", nationality: "프랑스", team: "바르셀로나", position: "CB", birthYear: 1998, number: 23 },
    { name: "Alejandro Balde", nameKo: "알레한드로 발데", nationality: "스페인", team: "바르셀로나", position: "LB", birthYear: 2003, number: 3 },
    { name: "Ferran Torres", nameKo: "페란 토레스", nationality: "스페인", team: "바르셀로나", position: "RW", birthYear: 2000, number: 7 },
    { name: "Joao Felix", nameKo: "주앙 펠릭스", nationality: "포르투갈", team: "바르셀로나", position: "ST", birthYear: 1999, number: 14 },
    { name: "Ilkay Gundogan", nameKo: "일카이 귄도간", nationality: "독일", team: "바르셀로나", position: "CM", birthYear: 1990, number: 22 },
    { name: "Andreas Christensen", nameKo: "안드레아스 크리스텐센", nationality: "덴마크", team: "바르셀로나", position: "CB", birthYear: 1996, number: 15 },
    // 아틀레티코 마드리드
    { name: "Antoine Griezmann", nameKo: "앙투안 그리즈만", nationality: "프랑스", team: "아틀레티코 마드리드", position: "ST", birthYear: 1991, number: 7 },
    { name: "Alvaro Morata", nameKo: "알바로 모라타", nationality: "스페인", team: "아틀레티코 마드리드", position: "ST", birthYear: 1992, number: 9 },
    { name: "Jan Oblak", nameKo: "얀 오블락", nationality: "슬로베니아", team: "아틀레티코 마드리드", position: "GK", birthYear: 1993, number: 13 },
    { name: "Marcos Llorente", nameKo: "마르코스 요렌테", nationality: "스페인", team: "아틀레티코 마드리드", position: "CM", birthYear: 1995, number: 14 },
    { name: "Rodrigo De Paul", nameKo: "로드리고 데 파울", nationality: "아르헨티나", team: "아틀레티코 마드리드", position: "CM", birthYear: 1994, number: 5 },
    { name: "Koke", nameKo: "코게", nationality: "스페인", team: "아틀레티코 마드리드", position: "CM", birthYear: 1992, number: 6 },
    { name: "Jose Maria Gimenez", nameKo: "호세 마리아 히메네스", nationality: "우루과이", team: "아틀레티코 마드리드", position: "CB", birthYear: 1995, number: 2 },
    { name: "Nahuel Molina", nameKo: "나우엘 몰리나", nationality: "아르헨티나", team: "아틀레티코 마드리드", position: "RB", birthYear: 1998, number: 16 },
    { name: "Memphis Depay", nameKo: "멤피스 데파이", nationality: "네덜란드", team: "아틀레티코 마드리드", position: "ST", birthYear: 1994, number: 94 },
    { name: "Samuel Lino", nameKo: "사무엘 리노", nationality: "브라질", team: "아틀레티코 마드리드", position: "LW", birthYear: 2000, number: 12 },
    { name: "Axel Witsel", nameKo: "악셀 비첼", nationality: "벨기에", team: "아틀레티코 마드리드", position: "CB", birthYear: 1989, number: 20 },
    // 레알 소시에다드
    { name: "Mikel Merino", nameKo: "미켈 메리노", nationality: "스페인", team: "레알 소시에다드", position: "CM", birthYear: 1996, number: 8 },
    { name: "Take Kubo", nameKo: "쿠보 다케후사", nationality: "일본", team: "레알 소시에다드", position: "RW", birthYear: 2001, number: 14 },
    { name: "Martin Zubimendi", nameKo: "마르틴 수비멘디", nationality: "스페인", team: "레알 소시에다드", position: "CDM", birthYear: 1999, number: 4 },
    { name: "Alexander Sorloth", nameKo: "알렉산더 쇠를로트", nationality: "노르웨이", team: "레알 소시에다드", position: "ST", birthYear: 1995, number: 19 },
    { name: "Brais Mendez", nameKo: "브라이스 멘데스", nationality: "스페인", team: "레알 소시에다드", position: "CAM", birthYear: 1997, number: 10 },
    { name: "Alex Remiro", nameKo: "알렉스 레미로", nationality: "스페인", team: "레알 소시에다드", position: "GK", birthYear: 1995, number: 1 },
    { name: "Robin Le Normand", nameKo: "로빈 르 노르망", nationality: "스페인", team: "레알 소시에다드", position: "CB", birthYear: 1996, number: 6 },
    // 빌바오
    { name: "Nico Williams", nameKo: "니코 윌리엄스", nationality: "스페인", team: "아틀레틱 빌바오", position: "LW", birthYear: 2002, number: 11 },
    { name: "Inaki Williams", nameKo: "이냐키 윌리엄스", nationality: "스페인", team: "아틀레틱 빌바오", position: "ST", birthYear: 1994, number: 9 },
    { name: "Oihan Sancet", nameKo: "오이한 산세트", nationality: "스페인", team: "아틀레틱 빌바오", position: "CAM", birthYear: 2000, number: 8 },
    { name: "Unai Simon", nameKo: "우나이 시몬", nationality: "스페인", team: "아틀레틱 빌바오", position: "GK", birthYear: 1997, number: 1 },
    { name: "Yuri Berchiche", nameKo: "유리 베르치체", nationality: "스페인", team: "아틀레틱 빌바오", position: "LB", birthYear: 1990, number: 17 },
    // 세비야
    { name: "Youssef En-Nesyri", nameKo: "유세프 엔네시리", nationality: "모로코", team: "세비야", position: "ST", birthYear: 1997, number: 15 },
    { name: "Lucas Ocampos", nameKo: "루카스 오캄포스", nationality: "아르헨티나", team: "세비야", position: "RW", birthYear: 1994, number: 5 },
    { name: "Ivan Rakitic", nameKo: "이반 라키티치", nationality: "크로아티아", team: "세비야", position: "CM", birthYear: 1988, number: 10 },
    { name: "Sergio Ramos", nameKo: "세르히오 라모스", nationality: "스페인", team: "세비야", position: "CB", birthYear: 1986, number: 4 },
    { name: "Jesus Navas", nameKo: "헤수스 나바스", nationality: "스페인", team: "세비야", position: "RB", birthYear: 1985, number: 16 },
    // 베티스
    { name: "Isco", nameKo: "이스코", nationality: "스페인", team: "베티스", position: "CAM", birthYear: 1992, number: 22 },
    { name: "Nabil Fekir", nameKo: "나빌 페키르", nationality: "프랑스", team: "베티스", position: "CAM", birthYear: 1993, number: 8 },
    { name: "Ayoze Perez", nameKo: "아요세 페레스", nationality: "스페인", team: "베티스", position: "ST", birthYear: 1993, number: 10 },
    { name: "Guido Rodriguez", nameKo: "기도 로드리게스", nationality: "아르헨티나", team: "베티스", position: "CDM", birthYear: 1994, number: 5 },
    { name: "Claudio Bravo", nameKo: "클라우디오 브라보", nationality: "칠레", team: "베티스", position: "GK", birthYear: 1983, number: 1 },
    // 비야레알
    { name: "Gerard Moreno", nameKo: "제라르드 모레노", nationality: "스페인", team: "비야레알", position: "ST", birthYear: 1992, number: 7 },
    { name: "Alex Baena", nameKo: "알렉스 바에나", nationality: "스페인", team: "비야레알", position: "CAM", birthYear: 2001, number: 16 },
    { name: "Arnaut Danjuma", nameKo: "아르나우트 단주마", nationality: "네덜란드", team: "비야레알", position: "LW", birthYear: 1997, number: 15 },
    { name: "Juan Foyth", nameKo: "후안 포이스", nationality: "아르헨티나", team: "비야레알", position: "RB", birthYear: 1998, number: 8 },
    { name: "Raul Albiol", nameKo: "라울 알비올", nationality: "스페인", team: "비야레알", position: "CB", birthYear: 1985, number: 3 },
    { name: "Pau Torres", nameKo: "파우 토레스", nationality: "스페인", team: "비야레알", position: "CB", birthYear: 1997, number: 4 },
    // 발렌시아
    { name: "Hugo Duro", nameKo: "우고 두로", nationality: "스페인", team: "발렌시아", position: "ST", birthYear: 1999, number: 9 },
    { name: "Pepelu", nameKo: "페펠루", nationality: "스페인", team: "발렌시아", position: "CM", birthYear: 1998, number: 18 },
    { name: "Giorgi Mamardashvili", nameKo: "기오르기 마마르다슈빌리", nationality: "조지아", team: "발렌시아", position: "GK", birthYear: 2000, number: 25 },
    { name: "Jose Gaya", nameKo: "호세 가야", nationality: "스페인", team: "발렌시아", position: "LB", birthYear: 1995, number: 14 },
    // 셀타 비고
    { name: "Iago Aspas", nameKo: "이아고 아스파스", nationality: "스페인", team: "셀타 비고", position: "ST", birthYear: 1987, number: 10 },
    { name: "Gabri Veiga", nameKo: "가브리 베이가", nationality: "스페인", team: "셀타 비고", position: "CAM", birthYear: 2002, number: 6 },
    { name: "Jorgen Strand Larsen", nameKo: "요르겐 스트란드 라르센", nationality: "노르웨이", team: "셀타 비고", position: "ST", birthYear: 2000, number: 9 },
    // 라스 팔마스
    { name: "Jonathan Viera", nameKo: "조나탄 비에라", nationality: "스페인", team: "라스 팔마스", position: "CAM", birthYear: 1989, number: 21 },
    { name: "Alberto Moleiro", nameKo: "알베르토 몰레이로", nationality: "스페인", team: "라스 팔마스", position: "CAM", birthYear: 2003, number: 10 },
    // 지로나
    { name: "Artem Dovbyk", nameKo: "아르템 도브비크", nationality: "우크라이나", team: "지로나", position: "ST", birthYear: 1997, number: 9 },
    { name: "Savio", nameKo: "사비우", nationality: "브라질", team: "지로나", position: "RW", birthYear: 2004, number: 10 },
    { name: "Aleix Garcia", nameKo: "알레이스 가르시아", nationality: "스페인", team: "지로나", position: "CM", birthYear: 1997, number: 17 },
    { name: "Viktor Tsygankov", nameKo: "빅토르 치간코프", nationality: "우크라이나", team: "지로나", position: "RW", birthYear: 1997, number: 15 },
    { name: "Yan Couto", nameKo: "얀 코우투", nationality: "브라질", team: "지로나", position: "RB", birthYear: 2002, number: 2 },
    { name: "Eric Garcia", nameKo: "에릭 가르시아", nationality: "스페인", team: "지로나", position: "CB", birthYear: 2001, number: 24 },
    { name: "Miguel Gutierrez", nameKo: "미겔 구티에레스", nationality: "스페인", team: "지로나", position: "LB", birthYear: 2001, number: 3 },
    { name: "Daley Blind", nameKo: "데일리 블린트", nationality: "네덜란드", team: "지로나", position: "CB", birthYear: 1990, number: 17 },
    // 오사수나
    { name: "Ante Budimir", nameKo: "안테 부디미르", nationality: "크로아티아", team: "오사수나", position: "ST", birthYear: 1991, number: 17 },
    { name: "Chimy Avila", nameKo: "치미 아빌라", nationality: "아르헨티나", team: "오사수나", position: "ST", birthYear: 1994, number: 9 },
    // 헤타페
    { name: "Borja Mayoral", nameKo: "보르하 마요랄", nationality: "스페인", team: "헤타페", position: "ST", birthYear: 1997, number: 21 },
    { name: "Mason Greenwood", nameKo: "메이슨 그린우드", nationality: "잉글랜드", team: "헤타페", position: "RW", birthYear: 2001, number: 11 },
    // 라요 바예카노
    { name: "Isi Palazon", nameKo: "이시 팔라손", nationality: "스페인", team: "라요 바예카노", position: "RW", birthYear: 1992, number: 21 },
    { name: "Raul de Tomas", nameKo: "라울 데 토마스", nationality: "스페인", team: "라요 바예카노", position: "ST", birthYear: 1994, number: 9 },
    // 마요르카
    { name: "Vedat Muriqi", nameKo: "베다트 무리치", nationality: "코소보", team: "마요르카", position: "ST", birthYear: 1994, number: 17 },
    { name: "Dani Rodriguez", nameKo: "다니 로드리게스", nationality: "스페인", team: "마요르카", position: "CM", birthYear: 1990, number: 14 },
    // 알메리아
    { name: "Leo Baptistao", nameKo: "레오 바프티스타오", nationality: "브라질", team: "알메리아", position: "ST", birthYear: 1992, number: 10 },
    { name: "Luis Suarez", nameKo: "루이스 수아레스", nationality: "콜롬비아", team: "알메리아", position: "ST", birthYear: 1997, number: 9 },
    // 카디스
    { name: "Chris Ramos", nameKo: "크리스 라모스", nationality: "스페인", team: "카디스", position: "ST", birthYear: 2001, number: 19 },
    { name: "Roger Marti", nameKo: "로저 마르티", nationality: "스페인", team: "카디스", position: "ST", birthYear: 1991, number: 9 },
    // 그라나다
    { name: "Myrto Uzuni", nameKo: "미르토 우주니", nationality: "알바니아", team: "그라나다", position: "LW", birthYear: 1995, number: 11 },
    { name: "Lucas Boye", nameKo: "루카스 보예", nationality: "아르헨티나", team: "그라나다", position: "ST", birthYear: 1996, number: 9 },
    // 알라베스
    { name: "Kike Garcia", nameKo: "키게 가르시아", nationality: "스페인", team: "알라베스", position: "ST", birthYear: 1989, number: 9 },
    { name: "Luis Rioja", nameKo: "루이스 리오하", nationality: "스페인", team: "알라베스", position: "LW", birthYear: 1993, number: 11 }
  ],
  "세리에A": [
    // 인터 밀란
    { name: "Lautaro Martinez", nameKo: "라우타로 마르티네스", nationality: "아르헨티나", team: "인터 밀란", position: "ST", birthYear: 1997, number: 10 },
    { name: "Marcus Thuram", nameKo: "마르쿠스 튀랑", nationality: "프랑스", team: "인터 밀란", position: "ST", birthYear: 1997, number: 9 },
    { name: "Nicolo Barella", nameKo: "니콜로 바렐라", nationality: "이탈리아", team: "인터 밀란", position: "CM", birthYear: 1997, number: 23 },
    { name: "Hakan Calhanoglu", nameKo: "하칸 찰하놀루", nationality: "터키", team: "인터 밀란", position: "CM", birthYear: 1994, number: 20 },
    { name: "Alessandro Bastoni", nameKo: "알레산드로 바스토니", nationality: "이탈리아", team: "인터 밀란", position: "CB", birthYear: 1999, number: 95 },
    { name: "Federico Dimarco", nameKo: "페데리코 디마르코", nationality: "이탈리아", team: "인터 밀란", position: "LB", birthYear: 1997, number: 32 },
    { name: "Henrikh Mkhitaryan", nameKo: "헨리흐 므키타리안", nationality: "아르메니아", team: "인터 밀란", position: "CM", birthYear: 1989, number: 22 },
    { name: "Denzel Dumfries", nameKo: "덴젤 뒴프리스", nationality: "네덜란드", team: "인터 밀란", position: "RB", birthYear: 1996, number: 2 },
    { name: "Francesco Acerbi", nameKo: "프란체스코 아체르비", nationality: "이탈리아", team: "인터 밀란", position: "CB", birthYear: 1988, number: 15 },
    { name: "Yann Sommer", nameKo: "얀 조머", nationality: "스위스", team: "인터 밀란", position: "GK", birthYear: 1988, number: 1 },
    { name: "Stefan de Vrij", nameKo: "스테판 더 프레이", nationality: "네덜란드", team: "인터 밀란", position: "CB", birthYear: 1992, number: 6 },
    { name: "Marko Arnautovic", nameKo: "마르코 아르나우토비치", nationality: "오스트리아", team: "인터 밀란", position: "ST", birthYear: 1989, number: 8 },
    // AC 밀란
    { name: "Rafael Leao", nameKo: "하파엘 레앙", nationality: "포르투갈", team: "AC 밀란", position: "LW", birthYear: 1999, number: 10 },
    { name: "Theo Hernandez", nameKo: "테오 에르난데스", nationality: "프랑스", team: "AC 밀란", position: "LB", birthYear: 1997, number: 19 },
    { name: "Mike Maignan", nameKo: "마이크 매냥", nationality: "프랑스", team: "AC 밀란", position: "GK", birthYear: 1995, number: 16 },
    { name: "Christian Pulisic", nameKo: "크리스티안 풀리식", nationality: "미국", team: "AC 밀란", position: "RW", birthYear: 1998, number: 11 },
    { name: "Tijjani Reijnders", nameKo: "티야니 레인더르스", nationality: "네덜란드", team: "AC 밀란", position: "CM", birthYear: 1998, number: 14 },
    { name: "Ruben Loftus-Cheek", nameKo: "루벤 로프터스-치크", nationality: "잉글랜드", team: "AC 밀란", position: "CM", birthYear: 1996, number: 8 },
    { name: "Ismael Bennacer", nameKo: "이스마엘 베나세르", nationality: "알제리", team: "AC 밀란", position: "CDM", birthYear: 1997, number: 4 },
    { name: "Fikayo Tomori", nameKo: "피카요 토모리", nationality: "잉글랜드", team: "AC 밀란", position: "CB", birthYear: 1997, number: 23 },
    { name: "Samuel Chukwueze", nameKo: "사무엘 추크우에제", nationality: "나이지리아", team: "AC 밀란", position: "RW", birthYear: 1999, number: 21 },
    { name: "Davide Calabria", nameKo: "다비데 칼라브리아", nationality: "이탈리아", team: "AC 밀란", position: "RB", birthYear: 1996, number: 2 },
    { name: "Noah Okafor", nameKo: "노아 오카포르", nationality: "스위스", team: "AC 밀란", position: "LW", birthYear: 2000, number: 17 },
    { name: "Olivier Giroud", nameKo: "올리비에 지루", nationality: "프랑스", team: "AC 밀란", position: "ST", birthYear: 1986, number: 9 },
    // 유벤투스
    { name: "Dusan Vlahovic", nameKo: "두샨 블라호비치", nationality: "세르비아", team: "유벤투스", position: "ST", birthYear: 2000, number: 9 },
    { name: "Federico Chiesa", nameKo: "페데리코 키에사", nationality: "이탈리아", team: "유벤투스", position: "RW", birthYear: 1997, number: 7 },
    { name: "Gleison Bremer", nameKo: "글레이송 브레머", nationality: "브라질", team: "유벤투스", position: "CB", birthYear: 1997, number: 3 },
    { name: "Manuel Locatelli", nameKo: "마누엘 로카텔리", nationality: "이탈리아", team: "유벤투스", position: "CM", birthYear: 1998, number: 5 },
    { name: "Adrien Rabiot", nameKo: "아드리앙 라비오", nationality: "프랑스", team: "유벤투스", position: "CM", birthYear: 1995, number: 25 },
    { name: "Wojciech Szczesny", nameKo: "보이치에흐 슈쳉스니", nationality: "폴란드", team: "유벤투스", position: "GK", birthYear: 1990, number: 1 },
    { name: "Filip Kostic", nameKo: "필리프 코스티치", nationality: "세르비아", team: "유벤투스", position: "LW", birthYear: 1992, number: 17 },
    { name: "Alex Sandro", nameKo: "알렉스 산드루", nationality: "브라질", team: "유벤투스", position: "LB", birthYear: 1991, number: 12 },
    { name: "Danilo", nameKo: "다닐루", nationality: "브라질", team: "유벤투스", position: "RB", birthYear: 1991, number: 6 },
    { name: "Kenan Yildiz", nameKo: "케난 이을디즈", nationality: "터키", team: "유벤투스", position: "LW", birthYear: 2005, number: 10 },
    { name: "Timothy Weah", nameKo: "티모시 웨아", nationality: "미국", team: "유벤투스", position: "RW", birthYear: 2000, number: 22 },
    // 나폴리
    { name: "Victor Osimhen", nameKo: "빅터 오시멘", nationality: "나이지리아", team: "나폴리", position: "ST", birthYear: 1998, number: 9 },
    { name: "Khvicha Kvaratskhelia", nameKo: "크비차 크바라츠헬리아", nationality: "조지아", team: "나폴리", position: "LW", birthYear: 2001, number: 77 },
    { name: "Giovanni Di Lorenzo", nameKo: "조반니 디 로렌초", nationality: "이탈리아", team: "나폴리", position: "RB", birthYear: 1993, number: 22 },
    { name: "Kim Min-jae", nameKo: "김민재", nationality: "대한민국", team: "나폴리", position: "CB", birthYear: 1996, number: 3 },
    { name: "Stanislav Lobotka", nameKo: "스타니슬라프 로보트카", nationality: "슬로바키아", team: "나폴리", position: "CDM", birthYear: 1994, number: 68 },
    { name: "Piotr Zielinski", nameKo: "피오트르 지엘린스키", nationality: "폴란드", team: "나폴리", position: "CM", birthYear: 1994, number: 20 },
    { name: "Amir Rrahmani", nameKo: "아미르 라흐마니", nationality: "코소보", team: "나폴리", position: "CB", birthYear: 1994, number: 13 },
    { name: "Alex Meret", nameKo: "알렉스 메레트", nationality: "이탈리아", team: "나폴리", position: "GK", birthYear: 1997, number: 1 },
    { name: "Matteo Politano", nameKo: "마테오 폴리타노", nationality: "이탈리아", team: "나폴리", position: "RW", birthYear: 1993, number: 21 },
    { name: "Giovanni Simeone", nameKo: "조반니 시메오네", nationality: "아르헨티나", team: "나폴리", position: "ST", birthYear: 1995, number: 18 },
    // AS 로마
    { name: "Paulo Dybala", nameKo: "파울로 디발라", nationality: "아르헨티나", team: "AS 로마", position: "CAM", birthYear: 1993, number: 21 },
    { name: "Romelu Lukaku", nameKo: "로멜루 루카쿠", nationality: "벨기에", team: "AS 로마", position: "ST", birthYear: 1993, number: 9 },
    { name: "Lorenzo Pellegrini", nameKo: "로렌초 펠레그리니", nationality: "이탈리아", team: "AS 로마", position: "CAM", birthYear: 1996, number: 7 },
    { name: "Gianluca Mancini", nameKo: "지안루카 만치니", nationality: "이탈리아", team: "AS 로마", position: "CB", birthYear: 1996, number: 23 },
    { name: "Chris Smalling", nameKo: "크리스 스몰링", nationality: "잉글랜드", team: "AS 로마", position: "CB", birthYear: 1989, number: 6 },
    { name: "Rui Patricio", nameKo: "루이 파트리시우", nationality: "포르투갈", team: "AS 로마", position: "GK", birthYear: 1988, number: 1 },
    { name: "Leandro Paredes", nameKo: "레안드로 파레데스", nationality: "아르헨티나", team: "AS 로마", position: "CM", birthYear: 1994, number: 16 },
    { name: "Stephan El Shaarawy", nameKo: "스테판 엘 샤라위", nationality: "이탈리아", team: "AS 로마", position: "LW", birthYear: 1992, number: 92 },
    // 라치오
    { name: "Ciro Immobile", nameKo: "치로 임모빌레", nationality: "이탈리아", team: "라치오", position: "ST", birthYear: 1990, number: 17 },
    { name: "Sergej Milinkovic-Savic", nameKo: "세르게이 밀린코비치-사비치", nationality: "세르비아", team: "라치오", position: "CM", birthYear: 1995, number: 21 },
    { name: "Luis Alberto", nameKo: "루이스 알베르토", nationality: "스페인", team: "라치오", position: "CAM", birthYear: 1992, number: 10 },
    { name: "Pedro", nameKo: "페드로", nationality: "스페인", team: "라치오", position: "RW", birthYear: 1987, number: 9 },
    { name: "Ivan Provedel", nameKo: "이반 프로베델", nationality: "이탈리아", team: "라치오", position: "GK", birthYear: 1994, number: 1 },
    { name: "Adam Marusic", nameKo: "아담 마루시치", nationality: "몬테네그로", team: "라치오", position: "RB", birthYear: 1992, number: 77 },
    { name: "Felipe Anderson", nameKo: "펠리피 안데르송", nationality: "브라질", team: "라치오", position: "RW", birthYear: 1993, number: 7 },
    { name: "Mattia Zaccagni", nameKo: "마티아 자카니", nationality: "이탈리아", team: "라치오", position: "LW", birthYear: 1995, number: 20 },
    // 아탈란타
    { name: "Ademola Lookman", nameKo: "아데몰라 루크만", nationality: "나이지리아", team: "아탈란타", position: "LW", birthYear: 1997, number: 11 },
    { name: "Gianluca Scamacca", nameKo: "지안루카 스카마카", nationality: "이탈리아", team: "아탈란타", position: "ST", birthYear: 1999, number: 90 },
    { name: "Teun Koopmeiners", nameKo: "튠 콥마이너르스", nationality: "네덜란드", team: "아탈란타", position: "CM", birthYear: 1998, number: 7 },
    { name: "Ederson", nameKo: "에데르송", nationality: "브라질", team: "아탈란타", position: "CM", birthYear: 1999, number: 13 },
    { name: "Mario Pasalic", nameKo: "마리오 파살리치", nationality: "크로아티아", team: "아탈란타", position: "CAM", birthYear: 1995, number: 88 },
    { name: "Juan Musso", nameKo: "후안 무소", nationality: "아르헨티나", team: "아탈란타", position: "GK", birthYear: 1994, number: 1 },
    { name: "Rafael Toloi", nameKo: "라파엘 톨로이", nationality: "이탈리아", team: "아탈란타", position: "CB", birthYear: 1990, number: 2 },
    // 피오렌티나
    { name: "Nico Gonzalez", nameKo: "니코 곤살레스", nationality: "아르헨티나", team: "피오렌티나", position: "RW", birthYear: 1998, number: 10 },
    { name: "Giacomo Bonaventura", nameKo: "자코모 보나벤투라", nationality: "이탈리아", team: "피오렌티나", position: "CM", birthYear: 1989, number: 5 },
    { name: "Luka Jovic", nameKo: "루카 요비치", nationality: "세르비아", team: "피오렌티나", position: "ST", birthYear: 1997, number: 7 },
    { name: "Pietro Terracciano", nameKo: "피에트로 테라치아노", nationality: "이탈리아", team: "피오렌티나", position: "GK", birthYear: 1990, number: 1 },
    { name: "Nikola Milenkovic", nameKo: "니콜라 밀렌코비치", nationality: "세르비아", team: "피오렌티나", position: "CB", birthYear: 1997, number: 4 },
    { name: "Riccardo Sottil", nameKo: "리카르도 소틸", nationality: "이탈리아", team: "피오렌티나", position: "LW", birthYear: 1999, number: 32 },
    { name: "Sofyan Amrabat", nameKo: "소피안 암라바트", nationality: "모로코", team: "피오렌티나", position: "CDM", birthYear: 1996, number: 4 },
    // 볼로냐
    { name: "Joshua Zirkzee", nameKo: "조슈아 지르크제", nationality: "네덜란드", team: "볼로냐", position: "ST", birthYear: 2001, number: 9 },
    { name: "Riccardo Orsolini", nameKo: "리카르도 오르솔리니", nationality: "이탈리아", team: "볼로냐", position: "RW", birthYear: 1997, number: 7 },
    { name: "Lewis Ferguson", nameKo: "루이스 퍼거슨", nationality: "스코틀랜드", team: "볼로냐", position: "CM", birthYear: 1999, number: 19 },
    { name: "Remo Freuler", nameKo: "레모 프로일러", nationality: "스위스", team: "볼로냐", position: "CM", birthYear: 1992, number: 8 },
    { name: "Sam Beukema", nameKo: "샘 뵈케마", nationality: "네덜란드", team: "볼로냐", position: "CB", birthYear: 1998, number: 31 },
    // 토리노
    { name: "Duvan Zapata", nameKo: "두반 사파타", nationality: "콜롬비아", team: "토리노", position: "ST", birthYear: 1991, number: 91 },
    { name: "Antonio Sanabria", nameKo: "안토니오 사나브리아", nationality: "파라과이", team: "토리노", position: "ST", birthYear: 1996, number: 9 },
    { name: "Nikola Vlasic", nameKo: "니콜라 블라시치", nationality: "크로아티아", team: "토리노", position: "CAM", birthYear: 1997, number: 10 },
    { name: "Vanja Milinkovic-Savic", nameKo: "반야 밀린코비치-사비치", nationality: "세르비아", team: "토리노", position: "GK", birthYear: 1997, number: 32 },
    { name: "Alessandro Buongiorno", nameKo: "알레산드로 부온지오르노", nationality: "이탈리아", team: "토리노", position: "CB", birthYear: 1999, number: 4 },
    // 몬자
    { name: "Gianluca Caprari", nameKo: "지안루카 카프라리", nationality: "이탈리아", team: "몬자", position: "ST", birthYear: 1993, number: 10 },
    { name: "Andrea Colpani", nameKo: "안드레아 콜파니", nationality: "이탈리아", team: "몬자", position: "CAM", birthYear: 1999, number: 28 },
    { name: "Matteo Pessina", nameKo: "마테오 페시나", nationality: "이탈리아", team: "몬자", position: "CM", birthYear: 1997, number: 32 },
    // 젠노아
    { name: "Albert Gudmundsson", nameKo: "알베르트 구드문드손", nationality: "아이슬란드", team: "제노아", position: "CAM", birthYear: 1997, number: 11 },
    { name: "Mateo Retegui", nameKo: "마테오 레테기", nationality: "아르헨티나", team: "제노아", position: "ST", birthYear: 1999, number: 19 },
    // 우디네세
    { name: "Gerard Deulofeu", nameKo: "제라르드 데울로페우", nationality: "스페인", team: "우디네세", position: "LW", birthYear: 1994, number: 10 },
    { name: "Lazar Samardzic", nameKo: "라자르 사마르지치", nationality: "세르비아", team: "우디네세", position: "CAM", birthYear: 2002, number: 24 },
    // 사수올로
    { name: "Domenico Berardi", nameKo: "도메니코 베라르디", nationality: "이탈리아", team: "사수올로", position: "RW", birthYear: 1994, number: 25 },
    { name: "Armand Lauriente", nameKo: "아르망 로리앙트", nationality: "프랑스", team: "사수올로", position: "LW", birthYear: 1998, number: 21 },
    // 레체
    { name: "Patrick Dorgu", nameKo: "패트릭 도르구", nationality: "덴마크", team: "레체", position: "LB", birthYear: 2004, number: 13 },
    // 엠폴리
    { name: "Francesco Caputo", nameKo: "프란체스코 카푸토", nationality: "이탈리아", team: "엠폴리", position: "ST", birthYear: 1987, number: 9 },
    // 프로시노네
    { name: "Nadir Zortea", nameKo: "나디르 조르테아", nationality: "이탈리아", team: "프로시노네", position: "RB", birthYear: 1999, number: 17 },
    // 칼리아리
    { name: "Leonardo Pavoletti", nameKo: "레오나르도 파볼레티", nationality: "이탈리아", team: "칼리아리", position: "ST", birthYear: 1988, number: 30 },
    { name: "Nicolas Viola", nameKo: "니콜라스 비올라", nationality: "이탈리아", team: "칼리아리", position: "CM", birthYear: 1989, number: 10 },
    // 헬라스 베로나
    { name: "Ondrej Duda", nameKo: "온드레이 두다", nationality: "슬로바키아", team: "헬라스 베로나", position: "CAM", birthYear: 1994, number: 16 },
    { name: "Thomas Henry", nameKo: "토마스 앙리", nationality: "프랑스", team: "헬라스 베로나", position: "ST", birthYear: 1994, number: 29 },
    // 살레르니타나
    { name: "Boulaye Dia", nameKo: "불라예 디아", nationality: "세네갈", team: "살레르니타나", position: "ST", birthYear: 1996, number: 9 },
    { name: "Antonio Candreva", nameKo: "안토니오 칸드레바", nationality: "이탈리아", team: "살레르니타나", position: "RM", birthYear: 1987, number: 87 }
  ],
  "리그1": [
    // 파리 생제르맹
    { name: "Ousmane Dembele", nameKo: "우스만 뎀벨레", nationality: "프랑스", team: "파리 생제르맹", position: "RW", birthYear: 1997, number: 10 },
    { name: "Randal Kolo Muani", nameKo: "랑달 콜로 무아니", nationality: "프랑스", team: "파리 생제르맹", position: "ST", birthYear: 1998, number: 23 },
    { name: "Achraf Hakimi", nameKo: "아크라프 하키미", nationality: "모로코", team: "파리 생제르맹", position: "RB", birthYear: 1998, number: 2 },
    { name: "Marquinhos", nameKo: "마르키뉴스", nationality: "브라질", team: "파리 생제르맹", position: "CB", birthYear: 1994, number: 5 },
    { name: "Gianluigi Donnarumma", nameKo: "지안루이지 돈나루마", nationality: "이탈리아", team: "파리 생제르맹", position: "GK", birthYear: 1999, number: 1 },
    { name: "Vitinha", nameKo: "비티냐", nationality: "포르투갈", team: "파리 생제르맹", position: "CM", birthYear: 2000, number: 17 },
    { name: "Warren Zaire-Emery", nameKo: "워렌 자이르-에메리", nationality: "프랑스", team: "파리 생제르맹", position: "CM", birthYear: 2006, number: 33 },
    { name: "Bradley Barcola", nameKo: "브래들리 바르콜라", nationality: "프랑스", team: "파리 생제르맹", position: "LW", birthYear: 2002, number: 29 },
    { name: "Lucas Hernandez", nameKo: "루카스 에르난데스", nationality: "프랑스", team: "파리 생제르맹", position: "CB", birthYear: 1996, number: 21 },
    { name: "Fabian Ruiz", nameKo: "파비안 루이스", nationality: "스페인", team: "파리 생제르맹", position: "CM", birthYear: 1996, number: 8 },
    { name: "Presnel Kimpembe", nameKo: "프레스넬 킴펨베", nationality: "프랑스", team: "파리 생제르맹", position: "CB", birthYear: 1995, number: 3 },
    { name: "Nuno Mendes", nameKo: "누누 멘데스", nationality: "포르투갈", team: "파리 생제르맹", position: "LB", birthYear: 2002, number: 25 },
    { name: "Manuel Ugarte", nameKo: "마누엘 우가르테", nationality: "우루과이", team: "파리 생제르맹", position: "CDM", birthYear: 2001, number: 4 },
    { name: "Lee Kang-in", nameKo: "이강인", nationality: "대한민국", team: "파리 생제르맹", position: "CAM", birthYear: 2001, number: 19 },
    { name: "Gonçalo Ramos", nameKo: "곤살루 하무스", nationality: "포르투갈", team: "파리 생제르맹", position: "ST", birthYear: 2001, number: 9 },
    // 마르세유
    { name: "Pierre-Emerick Aubameyang", nameKo: "피에르-에메릭 오바메양", nationality: "가봉", team: "올림피크 마르세유", position: "ST", birthYear: 1989, number: 10 },
    { name: "Matteo Guendouzi", nameKo: "마테오 겐두지", nationality: "프랑스", team: "올림피크 마르세유", position: "CM", birthYear: 1999, number: 6 },
    { name: "Jordan Veretout", nameKo: "조르당 베레투", nationality: "프랑스", team: "올림피크 마르세유", position: "CM", birthYear: 1993, number: 27 },
    { name: "Jonathan Clauss", nameKo: "조나탕 클로스", nationality: "프랑스", team: "올림피크 마르세유", position: "RB", birthYear: 1992, number: 7 },
    { name: "Pau Lopez", nameKo: "파우 로페스", nationality: "스페인", team: "올림피크 마르세유", position: "GK", birthYear: 1994, number: 16 },
    { name: "Chancel Mbemba", nameKo: "샹셀 음벰바", nationality: "콩고민주공화국", team: "올림피크 마르세유", position: "CB", birthYear: 1994, number: 99 },
    { name: "Amine Harit", nameKo: "아민 아리트", nationality: "모로코", team: "올림피크 마르세유", position: "CAM", birthYear: 1997, number: 11 },
    { name: "Iliman Ndiaye", nameKo: "일리만 은디아예", nationality: "세네갈", team: "올림피크 마르세유", position: "ST", birthYear: 2000, number: 10 },
    // 모나코
    { name: "Wissam Ben Yedder", nameKo: "위삼 벤 예데르", nationality: "프랑스", team: "AS 모나코", position: "ST", birthYear: 1990, number: 9 },
    { name: "Youssouf Fofana", nameKo: "유수프 포파나", nationality: "프랑스", team: "AS 모나코", position: "CM", birthYear: 1999, number: 19 },
    { name: "Aleksandr Golovin", nameKo: "알렉산드르 골로빈", nationality: "러시아", team: "AS 모나코", position: "CAM", birthYear: 1996, number: 17 },
    { name: "Takumi Minamino", nameKo: "미나미노 다쿠미", nationality: "일본", team: "AS 모나코", position: "LW", birthYear: 1995, number: 18 },
    { name: "Guillermo Maripan", nameKo: "기예르모 마리판", nationality: "칠레", team: "AS 모나코", position: "CB", birthYear: 1994, number: 3 },
    { name: "Vanderson", nameKo: "반데르송", nationality: "브라질", team: "AS 모나코", position: "RB", birthYear: 2001, number: 2 },
    { name: "Breel Embolo", nameKo: "브릴 엠볼로", nationality: "스위스", team: "AS 모나코", position: "ST", birthYear: 1997, number: 36 },
    { name: "Denis Zakaria", nameKo: "데니스 자카리아", nationality: "스위스", team: "AS 모나코", position: "CDM", birthYear: 1996, number: 33 },
    { name: "Eliesse Ben Seghir", nameKo: "엘리에스 벤 세기르", nationality: "모로코", team: "AS 모나코", position: "LW", birthYear: 2005, number: 47 },
    // 릴
    { name: "Jonathan David", nameKo: "조나단 데이비드", nationality: "캐나다", team: "릴", position: "ST", birthYear: 2000, number: 9 },
    { name: "Yusuf Yazici", nameKo: "유수프 야즈즈", nationality: "터키", team: "릴", position: "CAM", birthYear: 1997, number: 12 },
    { name: "Remy Cabella", nameKo: "레미 카벨라", nationality: "프랑스", team: "릴", position: "CAM", birthYear: 1990, number: 7 },
    { name: "Benjamin Andre", nameKo: "벵자맹 앙드레", nationality: "프랑스", team: "릴", position: "CDM", birthYear: 1990, number: 21 },
    { name: "Lucas Chevalier", nameKo: "루카스 슈발리에", nationality: "프랑스", team: "릴", position: "GK", birthYear: 2001, number: 30 },
    { name: "Tiago Santos", nameKo: "티아구 산투스", nationality: "포르투갈", team: "릴", position: "RB", birthYear: 2002, number: 28 },
    { name: "Leny Yoro", nameKo: "레니 요로", nationality: "프랑스", team: "릴", position: "CB", birthYear: 2005, number: 15 },
    { name: "Gabriel Gudmundsson", nameKo: "가브리엘 구드문드손", nationality: "스웨덴", team: "릴", position: "LB", birthYear: 1999, number: 3 },
    // 리옹
    { name: "Alexandre Lacazette", nameKo: "알렉상드르 라카제트", nationality: "프랑스", team: "올림피크 리옹", position: "ST", birthYear: 1991, number: 10 },
    { name: "Rayan Cherki", nameKo: "라얀 셰르키", nationality: "프랑스", team: "올림피크 리옹", position: "CAM", birthYear: 2003, number: 18 },
    { name: "Corentin Tolisso", nameKo: "코랑탱 톨리소", nationality: "프랑스", team: "올림피크 리옹", position: "CM", birthYear: 1994, number: 88 },
    { name: "Nicolas Tagliafico", nameKo: "니콜라스 탈리아피코", nationality: "아르헨티나", team: "올림피크 리옹", position: "LB", birthYear: 1992, number: 3 },
    { name: "Anthony Lopes", nameKo: "안토니 로페스", nationality: "포르투갈", team: "올림피크 리옹", position: "GK", birthYear: 1990, number: 1 },
    { name: "Jake O'Brien", nameKo: "제이크 오브라이언", nationality: "아일랜드", team: "올림피크 리옹", position: "CB", birthYear: 2001, number: 5 },
    { name: "Gift Orban", nameKo: "기프트 오르반", nationality: "나이지리아", team: "올림피크 리옹", position: "ST", birthYear: 2002, number: 14 },
    { name: "Mama Balde", nameKo: "마마 발데", nationality: "기니비사우", team: "올림피크 리옹", position: "LW", birthYear: 1996, number: 7 },
    // 렌
    { name: "Amine Gouiri", nameKo: "아민 구이리", nationality: "프랑스", team: "렌", position: "ST", birthYear: 2000, number: 11 },
    { name: "Martin Terrier", nameKo: "마르탱 테리에", nationality: "프랑스", team: "렌", position: "LW", birthYear: 1997, number: 7 },
    { name: "Benjamin Bourigeaud", nameKo: "벵자맹 부리고", nationality: "프랑스", team: "렌", position: "CM", birthYear: 1994, number: 14 },
    { name: "Steve Mandanda", nameKo: "스테브 망당다", nationality: "프랑스", team: "렌", position: "GK", birthYear: 1985, number: 16 },
    { name: "Arnaud Kalimuendo", nameKo: "아르노 칼리무엔도", nationality: "프랑스", team: "렌", position: "ST", birthYear: 2002, number: 22 },
    { name: "Desire Doue", nameKo: "데지레 두에", nationality: "프랑스", team: "렌", position: "CAM", birthYear: 2005, number: 14 },
    // 니스
    { name: "Terem Moffi", nameKo: "테렘 모피", nationality: "나이지리아", team: "니스", position: "ST", birthYear: 1999, number: 9 },
    { name: "Ross Barkley", nameKo: "로스 바클리", nationality: "잉글랜드", team: "니스", position: "CM", birthYear: 1993, number: 8 },
    { name: "Nicolas Pepe", nameKo: "니콜라 페페", nationality: "코트디부아르", team: "니스", position: "RW", birthYear: 1995, number: 18 },
    { name: "Marcin Bulka", nameKo: "마르친 불카", nationality: "폴란드", team: "니스", position: "GK", birthYear: 1999, number: 25 },
    { name: "Jean-Clair Todibo", nameKo: "장-클레어 토디보", nationality: "프랑스", team: "니스", position: "CB", birthYear: 1999, number: 6 },
    { name: "Jeremie Boga", nameKo: "제레미 보가", nationality: "코트디부아르", team: "니스", position: "LW", birthYear: 1997, number: 7 },
    // 랑스
    { name: "Folarin Balogun", nameKo: "폴라린 발로건", nationality: "미국", team: "랑스", position: "ST", birthYear: 2001, number: 9 },
    { name: "Marshall Munetsi", nameKo: "마샬 무네치", nationality: "짐바브웨", team: "랑스", position: "CM", birthYear: 1996, number: 19 },
    { name: "Martin Adeline", nameKo: "마르탱 아델린", nationality: "프랑스", team: "랑스", position: "CM", birthYear: 2003, number: 14 },
    { name: "Yehvann Diouf", nameKo: "예반 디우프", nationality: "프랑스", team: "랑스", position: "GK", birthYear: 1999, number: 1 },
    { name: "Will Still", nameKo: "윌 스틸", nationality: "벨기에", team: "랑스", position: "CB", birthYear: 1993, number: 4 },
    // 스트라스부르
    { name: "Habib Diarra", nameKo: "아비브 디아라", nationality: "말리", team: "스트라스부르", position: "CM", birthYear: 2004, number: 8 },
    { name: "Lebo Mothiba", nameKo: "레보 모티바", nationality: "남아프리카공화국", team: "스트라스부르", position: "ST", birthYear: 1996, number: 10 },
    { name: "Kevin Gameiro", nameKo: "케빈 가메이루", nationality: "프랑스", team: "스트라스부르", position: "ST", birthYear: 1987, number: 7 },
    // 낭트
    { name: "Mostafa Mohamed", nameKo: "모스타파 무함메드", nationality: "이집트", team: "낭트", position: "ST", birthYear: 1997, number: 9 },
    { name: "Moses Simon", nameKo: "모세스 시몬", nationality: "나이지리아", team: "낭트", position: "LW", birthYear: 1995, number: 27 },
    { name: "Pedro Chirivella", nameKo: "페드로 치리벨라", nationality: "스페인", team: "낭트", position: "CM", birthYear: 1997, number: 6 },
    { name: "Alban Lafont", nameKo: "알방 라퐁", nationality: "프랑스", team: "낭트", position: "GK", birthYear: 1999, number: 1 },
    // 몽펠리에
    { name: "Elye Wahi", nameKo: "엘리 와이", nationality: "프랑스", team: "몽펠리에", position: "ST", birthYear: 2003, number: 9 },
    { name: "Teji Savanier", nameKo: "테지 사바니에", nationality: "프랑스", team: "몽펠리에", position: "CM", birthYear: 1991, number: 11 },
    { name: "Jordan Ferri", nameKo: "조르당 페리", nationality: "프랑스", team: "몽펠리에", position: "CM", birthYear: 1992, number: 14 },
    { name: "Arnaud Nordin", nameKo: "아르노 노르댕", nationality: "프랑스", team: "몽펠리에", position: "LW", birthYear: 1998, number: 20 },
    // 브레스트
    { name: "Martin Satriano", nameKo: "마르틴 사트리아노", nationality: "우루과이", team: "브레스트", position: "ST", birthYear: 2001, number: 9 },
    { name: "Steve Mounie", nameKo: "스테브 무니에", nationality: "베냉", team: "브레스트", position: "ST", birthYear: 1994, number: 17 },
    { name: "Pierre Lees-Melou", nameKo: "피에르 레-멜루", nationality: "프랑스", team: "브레스트", position: "CM", birthYear: 1993, number: 8 },
    { name: "Marco Bizot", nameKo: "마르코 비조트", nationality: "네덜란드", team: "브레스트", position: "GK", birthYear: 1991, number: 1 },
    { name: "Romain Del Castillo", nameKo: "로맹 델 카스티요", nationality: "프랑스", team: "브레스트", position: "RW", birthYear: 1996, number: 7 },
    // 툴루즈
    { name: "Thijs Dallinga", nameKo: "테이스 달링하", nationality: "네덜란드", team: "툴루즈", position: "ST", birthYear: 2000, number: 9 },
    { name: "Zakaria Aboukhlal", nameKo: "자카리아 아부클랄", nationality: "모로코", team: "툴루즈", position: "LW", birthYear: 2000, number: 15 },
    { name: "Fares Chaibi", nameKo: "파레스 샤이비", nationality: "알제리", team: "툴루즈", position: "CAM", birthYear: 2003, number: 10 },
    { name: "Guillaume Restes", nameKo: "기욤 레스트", nationality: "프랑스", team: "툴루즈", position: "GK", birthYear: 2005, number: 1 },
    { name: "Aron Donnum", nameKo: "아론 도눔", nationality: "노르웨이", team: "툴루즈", position: "LW", birthYear: 1998, number: 17 },
    // 르아브르
    { name: "Andre Ayew", nameKo: "앙드레 아예", nationality: "가나", team: "르아브르", position: "ST", birthYear: 1989, number: 10 },
    { name: "Nabil Alioui", nameKo: "나빌 알리우이", nationality: "프랑스", team: "르아브르", position: "ST", birthYear: 2002, number: 9 },
    { name: "Arouna Sangante", nameKo: "아루나 상간테", nationality: "말리", team: "르아브르", position: "RB", birthYear: 2001, number: 2 },
    // 클레르몽
    { name: "Mohamed Bayo", nameKo: "모하메드 바요", nationality: "기니", team: "클레르몽", position: "ST", birthYear: 1998, number: 9 },
    { name: "Elbasan Rashani", nameKo: "엘바산 라샤니", nationality: "코소보", team: "클레르몽", position: "RW", birthYear: 1993, number: 7 },
    { name: "Johan Gastien", nameKo: "요한 가스티앵", nationality: "프랑스", team: "클레르몽", position: "CM", birthYear: 1988, number: 27 },
    // 로리앙
    { name: "Bamba Dieng", nameKo: "밤바 디엥", nationality: "세네갈", team: "로리앙", position: "ST", birthYear: 2000, number: 9 },
    { name: "Dango Ouattara", nameKo: "당고 와타라", nationality: "부르키나파소", team: "로리앙", position: "RW", birthYear: 2002, number: 11 },
    { name: "Darlin Yongwa", nameKo: "달린 용와", nationality: "카메룬", team: "로리앙", position: "CM", birthYear: 2002, number: 25 },
    // 멧
    { name: "Matthieu Udol", nameKo: "마티외 우돌", nationality: "프랑스", team: "멧", position: "LB", birthYear: 1996, number: 22 },
    { name: "Georges Mikautadze", nameKo: "게오르게스 미카우타제", nationality: "조지아", team: "멧", position: "ST", birthYear: 2000, number: 69 },
    { name: "Lamine Camara", nameKo: "라민 카마라", nationality: "세네갈", team: "멧", position: "CM", birthYear: 2004, number: 8 }
  ]
};

// 현재 선택된 리그의 선수 목록
let players = [];
