const allPlayers = {
  "프리미어리그": [
    // 맨체스터 시티
    { name: "Erling Haaland", nameKo: "엘링 홀란드", nationality: "노르웨이", team: "맨체스터 시티", position: "ST", birthYear: 2000, number: 9 },
    { name: "Kevin De Bruyne", nameKo: "케빈 더 브라위너", nationality: "벨기에", team: "맨체스터 시티", position: "CM", birthYear: 1991, number: 17 },
    { name: "Phil Foden", nameKo: "필 포든", nationality: "잉글랜드", team: "맨체스터 시티", position: "RW", birthYear: 2000, number: 47 },
    { name: "Bernardo Silva", nameKo: "베르나르두 실바", nationality: "포르투갈", team: "맨체스터 시티", position: "CM", birthYear: 1994, number: 20 },
    { name: "Rodri", nameKo: "로드리", nationality: "스페인", team: "맨체스터 시티", position: "CDM", birthYear: 1996, number: 16 },
    { name: "Jack Grealish", nameKo: "잭 그릴리쉬", nationality: "잉글랜드", team: "맨체스터 시티", position: "LW", birthYear: 1995, number: 10 },
    { name: "John Stones", nameKo: "존 스톤스", nationality: "잉글랜드", team: "맨체스터 시티", position: "CB", birthYear: 1994, number: 5 },
    { name: "Ruben Dias", nameKo: "루벤 디아스", nationality: "포르투갈", team: "맨체스터 시티", position: "CB", birthYear: 1997, number: 3 },
    { name: "Kyle Walker", nameKo: "카일 워커", nationality: "잉글랜드", team: "맨체스터 시티", position: "RB", birthYear: 1990, number: 2 },
    { name: "Ederson", nameKo: "에데르송", nationality: "브라질", team: "맨체스터 시티", position: "GK", birthYear: 1993, number: 31 },
    { name: "Julian Alvarez", nameKo: "훌리안 알바레스", nationality: "아르헨티나", team: "맨체스터 시티", position: "ST", birthYear: 2000, number: 19 },
    { name: "Mateo Kovacic", nameKo: "마테오 코바치치", nationality: "크로아티아", team: "맨체스터 시티", position: "CM", birthYear: 1994, number: 8 },
    // 리버풀
    { name: "Mohamed Salah", nameKo: "모하메드 살라", nationality: "이집트", team: "리버풀", position: "RW", birthYear: 1992, number: 11 },
    { name: "Virgil van Dijk", nameKo: "버질 반 다이크", nationality: "네덜란드", team: "리버풀", position: "CB", birthYear: 1991, number: 4 },
    { name: "Trent Alexander-Arnold", nameKo: "트렌트 알렉산더-아놀드", nationality: "잉글랜드", team: "리버풀", position: "RB", birthYear: 1998, number: 66 },
    { name: "Darwin Nunez", nameKo: "다르윈 누녜스", nationality: "우루과이", team: "리버풀", position: "ST", birthYear: 1999, number: 9 },
    { name: "Alisson", nameKo: "알리송", nationality: "브라질", team: "리버풀", position: "GK", birthYear: 1992, number: 1 },
    { name: "Luis Diaz", nameKo: "루이스 디아스", nationality: "콜롬비아", team: "리버풀", position: "LW", birthYear: 1997, number: 7 },
    { name: "Cody Gakpo", nameKo: "코디 각포", nationality: "네덜란드", team: "리버풀", position: "LW", birthYear: 1999, number: 18 },
    { name: "Dominik Szoboszlai", nameKo: "도미니크 소보슬라이", nationality: "헝가리", team: "리버풀", position: "CM", birthYear: 2000, number: 8 },
    { name: "Alexis Mac Allister", nameKo: "알렉시스 맥 알리스터", nationality: "아르헨티나", team: "리버풀", position: "CM", birthYear: 1998, number: 10 },
    { name: "Wataru Endo", nameKo: "엔도 와타루", nationality: "일본", team: "리버풀", position: "CDM", birthYear: 1993, number: 3 },
    { name: "Ibrahima Konate", nameKo: "이브라히마 코나테", nationality: "프랑스", team: "리버풀", position: "CB", birthYear: 1999, number: 5 },
    { name: "Andrew Robertson", nameKo: "앤드류 로버트슨", nationality: "스코틀랜드", team: "리버풀", position: "LB", birthYear: 1994, number: 26 },
    { name: "Diogo Jota", nameKo: "디오구 조타", nationality: "포르투갈", team: "리버풀", position: "LW", birthYear: 1996, number: 20 },
    // 아스널
    { name: "Bukayo Saka", nameKo: "부카요 사카", nationality: "잉글랜드", team: "아스널", position: "RW", birthYear: 2001, number: 7 },
    { name: "Martin Odegaard", nameKo: "마르틴 외데고르", nationality: "노르웨이", team: "아스널", position: "CAM", birthYear: 1998, number: 8 },
    { name: "William Saliba", nameKo: "윌리엄 살리바", nationality: "프랑스", team: "아스널", position: "CB", birthYear: 2001, number: 2 },
    { name: "Declan Rice", nameKo: "데클란 라이스", nationality: "잉글랜드", team: "아스널", position: "CDM", birthYear: 1999, number: 41 },
    { name: "Gabriel Jesus", nameKo: "가브리엘 제주스", nationality: "브라질", team: "아스널", position: "ST", birthYear: 1997, number: 9 },
    { name: "Gabriel Martinelli", nameKo: "가브리엘 마르티넬리", nationality: "브라질", team: "아스널", position: "LW", birthYear: 2001, number: 11 },
    { name: "Gabriel Magalhaes", nameKo: "가브리엘 마갈량이스", nationality: "브라질", team: "아스널", position: "CB", birthYear: 1997, number: 6 },
    { name: "Ben White", nameKo: "벤 화이트", nationality: "잉글랜드", team: "아스널", position: "RB", birthYear: 1997, number: 4 },
    { name: "David Raya", nameKo: "다비드 라야", nationality: "스페인", team: "아스널", position: "GK", birthYear: 1995, number: 22 },
    { name: "Kai Havertz", nameKo: "카이 하베르츠", nationality: "독일", team: "아스널", position: "ST", birthYear: 1999, number: 29 },
    { name: "Leandro Trossard", nameKo: "레안드로 트로사르", nationality: "벨기에", team: "아스널", position: "LW", birthYear: 1994, number: 19 },
    { name: "Oleksandr Zinchenko", nameKo: "올렉산드르 진첸코", nationality: "우크라이나", team: "아스널", position: "LB", birthYear: 1996, number: 35 },
    // 맨체스터 유나이티드
    { name: "Marcus Rashford", nameKo: "마커스 래시포드", nationality: "잉글랜드", team: "맨체스터 유나이티드", position: "LW", birthYear: 1997, number: 10 },
    { name: "Bruno Fernandes", nameKo: "브루노 페르난데스", nationality: "포르투갈", team: "맨체스터 유나이티드", position: "CAM", birthYear: 1994, number: 8 },
    { name: "Casemiro", nameKo: "카세미루", nationality: "브라질", team: "맨체스터 유나이티드", position: "CDM", birthYear: 1992, number: 18 },
    { name: "Rasmus Hojlund", nameKo: "라스무스 회일룬", nationality: "덴마크", team: "맨체스터 유나이티드", position: "ST", birthYear: 2003, number: 11 },
    { name: "Andre Onana", nameKo: "앙드레 오나나", nationality: "카메룬", team: "맨체스터 유나이티드", position: "GK", birthYear: 1996, number: 24 },
    { name: "Lisandro Martinez", nameKo: "리산드로 마르티네스", nationality: "아르헨티나", team: "맨체스터 유나이티드", position: "CB", birthYear: 1998, number: 6 },
    { name: "Alejandro Garnacho", nameKo: "알레한드로 가르나초", nationality: "아르헨티나", team: "맨체스터 유나이티드", position: "LW", birthYear: 2004, number: 17 },
    { name: "Kobbie Mainoo", nameKo: "코비 메이누", nationality: "잉글랜드", team: "맨체스터 유나이티드", position: "CM", birthYear: 2005, number: 37 },
    { name: "Diogo Dalot", nameKo: "디오구 달로트", nationality: "포르투갈", team: "맨체스터 유나이티드", position: "RB", birthYear: 1999, number: 20 },
    { name: "Luke Shaw", nameKo: "루크 쇼", nationality: "잉글랜드", team: "맨체스터 유나이티드", position: "LB", birthYear: 1995, number: 23 },
    { name: "Raphael Varane", nameKo: "라파엘 바란", nationality: "프랑스", team: "맨체스터 유나이티드", position: "CB", birthYear: 1993, number: 19 },
    { name: "Mason Mount", nameKo: "메이슨 마운트", nationality: "잉글랜드", team: "맨체스터 유나이티드", position: "CAM", birthYear: 1999, number: 7 },
    // 첼시
    { name: "Cole Palmer", nameKo: "콜 팔머", nationality: "잉글랜드", team: "첼시", position: "CAM", birthYear: 2002, number: 20 },
    { name: "Enzo Fernandez", nameKo: "엔소 페르난데스", nationality: "아르헨티나", team: "첼시", position: "CM", birthYear: 2001, number: 8 },
    { name: "Reece James", nameKo: "리스 제임스", nationality: "잉글랜드", team: "첼시", position: "RB", birthYear: 1999, number: 24 },
    { name: "Nicolas Jackson", nameKo: "니콜라스 잭슨", nationality: "세네갈", team: "첼시", position: "ST", birthYear: 2001, number: 15 },
    { name: "Moises Caicedo", nameKo: "모이세스 카이세도", nationality: "에콰도르", team: "첼시", position: "CDM", birthYear: 2001, number: 25 },
    { name: "Raheem Sterling", nameKo: "라힘 스털링", nationality: "잉글랜드", team: "첼시", position: "LW", birthYear: 1994, number: 17 },
    { name: "Noni Madueke", nameKo: "노니 마두에케", nationality: "잉글랜드", team: "첼시", position: "RW", birthYear: 2002, number: 11 },
    { name: "Malo Gusto", nameKo: "말로 구스토", nationality: "프랑스", team: "첼시", position: "RB", birthYear: 2003, number: 27 },
    { name: "Levi Colwill", nameKo: "레비 콜윌", nationality: "잉글랜드", team: "첼시", position: "CB", birthYear: 2003, number: 26 },
    { name: "Robert Sanchez", nameKo: "로베르트 산체스", nationality: "스페인", team: "첼시", position: "GK", birthYear: 1997, number: 1 },
    { name: "Conor Gallagher", nameKo: "코너 갤러거", nationality: "잉글랜드", team: "첼시", position: "CM", birthYear: 2000, number: 23 },
    { name: "Thiago Silva", nameKo: "치아구 실바", nationality: "브라질", team: "첼시", position: "CB", birthYear: 1984, number: 6 },
    // 토트넘
    { name: "Son Heung-min", nameKo: "손흥민", nationality: "대한민국", team: "토트넘", position: "LW", birthYear: 1992, number: 7 },
    { name: "James Maddison", nameKo: "제임스 매디슨", nationality: "잉글랜드", team: "토트넘", position: "CAM", birthYear: 1996, number: 10 },
    { name: "Richarlison", nameKo: "히샤를리송", nationality: "브라질", team: "토트넘", position: "ST", birthYear: 1997, number: 9 },
    { name: "Cristian Romero", nameKo: "크리스티안 로메로", nationality: "아르헨티나", team: "토트넘", position: "CB", birthYear: 1998, number: 17 },
    { name: "Guglielmo Vicario", nameKo: "굴리엘모 비카리오", nationality: "이탈리아", team: "토트넘", position: "GK", birthYear: 1996, number: 13 },
    { name: "Dejan Kulusevski", nameKo: "데얀 쿨루세프스키", nationality: "스웨덴", team: "토트넘", position: "RW", birthYear: 2000, number: 21 },
    { name: "Brennan Johnson", nameKo: "브레넌 존슨", nationality: "웨일스", team: "토트넘", position: "RW", birthYear: 2001, number: 19 },
    { name: "Micky van de Ven", nameKo: "미키 반 더 벤", nationality: "네덜란드", team: "토트넘", position: "CB", birthYear: 2001, number: 37 },
    { name: "Yves Bissouma", nameKo: "이브 비수마", nationality: "말리", team: "토트넘", position: "CDM", birthYear: 1996, number: 38 },
    { name: "Pedro Porro", nameKo: "페드로 포로", nationality: "스페인", team: "토트넘", position: "RB", birthYear: 1999, number: 23 },
    { name: "Destiny Udogie", nameKo: "데스티니 우도지에", nationality: "이탈리아", team: "토트넘", position: "LB", birthYear: 2002, number: 13 },
    // 뉴캐슬
    { name: "Alexander Isak", nameKo: "알렉산더 이삭", nationality: "스웨덴", team: "뉴캐슬", position: "ST", birthYear: 1999, number: 14 },
    { name: "Bruno Guimaraes", nameKo: "브루노 기마랑이스", nationality: "브라질", team: "뉴캐슬", position: "CM", birthYear: 1997, number: 39 },
    { name: "Sandro Tonali", nameKo: "산드로 토날리", nationality: "이탈리아", team: "뉴캐슬", position: "CM", birthYear: 2000, number: 8 },
    { name: "Anthony Gordon", nameKo: "앤서니 고든", nationality: "잉글랜드", team: "뉴캐슬", position: "LW", birthYear: 2001, number: 10 },
    { name: "Kieran Trippier", nameKo: "키어런 트리피어", nationality: "잉글랜드", team: "뉴캐슬", position: "RB", birthYear: 1990, number: 2 },
    { name: "Nick Pope", nameKo: "닉 포프", nationality: "잉글랜드", team: "뉴캐슬", position: "GK", birthYear: 1992, number: 22 },
    { name: "Sven Botman", nameKo: "스벤 보트만", nationality: "네덜란드", team: "뉴캐슬", position: "CB", birthYear: 2000, number: 4 },
    { name: "Joelinton", nameKo: "조엘링통", nationality: "브라질", team: "뉴캐슬", position: "CM", birthYear: 1996, number: 7 },
    { name: "Harvey Barnes", nameKo: "하비 반스", nationality: "잉글랜드", team: "뉴캐슬", position: "LW", birthYear: 1997, number: 11 },
    // 아스톤 빌라
    { name: "Ollie Watkins", nameKo: "올리 왓킨스", nationality: "잉글랜드", team: "아스톤 빌라", position: "ST", birthYear: 1995, number: 11 },
    { name: "Emi Martinez", nameKo: "에미 마르티네스", nationality: "아르헨티나", team: "아스톤 빌라", position: "GK", birthYear: 1992, number: 1 },
    { name: "Leon Bailey", nameKo: "레온 베일리", nationality: "자메이카", team: "아스톤 빌라", position: "RW", birthYear: 1997, number: 31 },
    { name: "Douglas Luiz", nameKo: "더글라스 루이스", nationality: "브라질", team: "아스톤 빌라", position: "CM", birthYear: 1998, number: 6 },
    { name: "John McGinn", nameKo: "존 맥긴", nationality: "스코틀랜드", team: "아스톤 빌라", position: "CM", birthYear: 1994, number: 7 },
    { name: "Moussa Diaby", nameKo: "무사 디아비", nationality: "프랑스", team: "아스톤 빌라", position: "RW", birthYear: 1999, number: 19 },
    { name: "Pau Torres", nameKo: "파우 토레스", nationality: "스페인", team: "아스톤 빌라", position: "CB", birthYear: 1997, number: 4 },
    { name: "Ezri Konsa", nameKo: "에즈리 콘사", nationality: "잉글랜드", team: "아스톤 빌라", position: "CB", birthYear: 1997, number: 15 },
    // 웨스트햄
    { name: "Jarrod Bowen", nameKo: "재로드 보웬", nationality: "잉글랜드", team: "웨스트햄", position: "RW", birthYear: 1996, number: 20 },
    { name: "Lucas Paqueta", nameKo: "루카스 파케타", nationality: "브라질", team: "웨스트햄", position: "CAM", birthYear: 1997, number: 11 },
    { name: "Mohammed Kudus", nameKo: "모하메드 쿠두스", nationality: "가나", team: "웨스트햄", position: "CAM", birthYear: 2000, number: 14 },
    { name: "James Ward-Prowse", nameKo: "제임스 워드-프라우즈", nationality: "잉글랜드", team: "웨스트햄", position: "CM", birthYear: 1994, number: 7 },
    { name: "Michail Antonio", nameKo: "미카일 안토니오", nationality: "자메이카", team: "웨스트햄", position: "ST", birthYear: 1990, number: 9 },
    // 브라이튼
    { name: "Kaoru Mitoma", nameKo: "미토마 카오루", nationality: "일본", team: "브라이튼", position: "LW", birthYear: 1997, number: 22 },
    { name: "Evan Ferguson", nameKo: "에반 퍼거슨", nationality: "아일랜드", team: "브라이튼", position: "ST", birthYear: 2004, number: 28 },
    { name: "Joao Pedro", nameKo: "주앙 페드루", nationality: "브라질", team: "브라이튼", position: "ST", birthYear: 2001, number: 9 },
    { name: "Julio Enciso", nameKo: "훌리오 엔시소", nationality: "파라과이", team: "브라이튼", position: "CAM", birthYear: 2004, number: 10 },
    { name: "Pascal Gross", nameKo: "파스칼 그로스", nationality: "독일", team: "브라이튼", position: "CM", birthYear: 1991, number: 13 },
    { name: "Lewis Dunk", nameKo: "루이스 덩크", nationality: "잉글랜드", team: "브라이튼", position: "CB", birthYear: 1991, number: 5 },
    // 울버햄튼
    { name: "Hwang Hee-chan", nameKo: "황희찬", nationality: "대한민국", team: "울버햄튼", position: "ST", birthYear: 1996, number: 11 },
    { name: "Matheus Cunha", nameKo: "마테우스 쿠냐", nationality: "브라질", team: "울버햄튼", position: "ST", birthYear: 1999, number: 12 },
    { name: "Pedro Neto", nameKo: "페드로 네투", nationality: "포르투갈", team: "울버햄튼", position: "LW", birthYear: 2000, number: 7 },
    { name: "Ruben Neves", nameKo: "루벤 네베스", nationality: "포르투갈", team: "울버햄튼", position: "CM", birthYear: 1997, number: 8 },
    { name: "Max Kilman", nameKo: "맥스 킬먼", nationality: "잉글랜드", team: "울버햄튼", position: "CB", birthYear: 1997, number: 15 },
    // 크리스탈 팰리스
    { name: "Michael Olise", nameKo: "마이클 올리세", nationality: "프랑스", team: "크리스탈 팰리스", position: "RW", birthYear: 2001, number: 7 },
    { name: "Eberechi Eze", nameKo: "에베레치 에제", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "CAM", birthYear: 1998, number: 10 },
    { name: "Marc Guehi", nameKo: "마크 게이", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "CB", birthYear: 2000, number: 6 },
    { name: "Adam Wharton", nameKo: "아담 와튼", nationality: "잉글랜드", team: "크리스탈 팰리스", position: "CM", birthYear: 2004, number: 62 },
    // 에버튼
    { name: "Dominic Calvert-Lewin", nameKo: "도미닉 칼버트-르윈", nationality: "잉글랜드", team: "에버튼", position: "ST", birthYear: 1997, number: 9 },
    { name: "Abdoulaye Doucoure", nameKo: "압둘라예 두쿠레", nationality: "말리", team: "에버튼", position: "CM", birthYear: 1993, number: 16 },
    { name: "Jordan Pickford", nameKo: "조던 픽포드", nationality: "잉글랜드", team: "에버튼", position: "GK", birthYear: 1994, number: 1 },
    // 풀럼
    { name: "Andreas Pereira", nameKo: "안드레아스 페레이라", nationality: "브라질", team: "풀럼", position: "CAM", birthYear: 1996, number: 18 },
    { name: "Joao Palhinha", nameKo: "주앙 팔리냐", nationality: "포르투갈", team: "풀럼", position: "CDM", birthYear: 1995, number: 26 },
    { name: "Antonee Robinson", nameKo: "안토니 로빈슨", nationality: "미국", team: "풀럼", position: "LB", birthYear: 1997, number: 33 },
    { name: "Bernd Leno", nameKo: "베른트 레노", nationality: "독일", team: "풀럼", position: "GK", birthYear: 1992, number: 1 }
  ],
  "라리가": [
    // 레알 마드리드
    { name: "Jude Bellingham", nameKo: "주드 벨링엄", nationality: "잉글랜드", team: "레알 마드리드", position: "CAM", birthYear: 2003, number: 5 },
    { name: "Vinicius Jr", nameKo: "비니시우스 주니어", nationality: "브라질", team: "레알 마드리드", position: "LW", birthYear: 2000, number: 7 },
    { name: "Kylian Mbappe", nameKo: "킬리안 음바페", nationality: "프랑스", team: "레알 마드리드", position: "ST", birthYear: 1998, number: 9 },
    { name: "Federico Valverde", nameKo: "페데리코 발베르데", nationality: "우루과이", team: "레알 마드리드", position: "CM", birthYear: 1998, number: 8 },
    { name: "Thibaut Courtois", nameKo: "티보 쿠르투아", nationality: "벨기에", team: "레알 마드리드", position: "GK", birthYear: 1992, number: 1 },
    { name: "Antonio Rudiger", nameKo: "안토니오 뤼디거", nationality: "독일", team: "레알 마드리드", position: "CB", birthYear: 1993, number: 22 },
    { name: "Luka Modric", nameKo: "루카 모드리치", nationality: "크로아티아", team: "레알 마드리드", position: "CM", birthYear: 1985, number: 10 },
    { name: "Rodrygo", nameKo: "호드리구", nationality: "브라질", team: "레알 마드리드", position: "RW", birthYear: 2001, number: 11 },
    { name: "Eduardo Camavinga", nameKo: "에두아르도 카마빙가", nationality: "프랑스", team: "레알 마드리드", position: "CM", birthYear: 2002, number: 12 },
    { name: "Aurelien Tchouameni", nameKo: "오렐리앙 추아메니", nationality: "프랑스", team: "레알 마드리드", position: "CDM", birthYear: 2000, number: 14 },
    { name: "Dani Carvajal", nameKo: "다니 카르바할", nationality: "스페인", team: "레알 마드리드", position: "RB", birthYear: 1992, number: 2 },
    { name: "Ferland Mendy", nameKo: "페를랑 망디", nationality: "프랑스", team: "레알 마드리드", position: "LB", birthYear: 1995, number: 23 },
    { name: "Eder Militao", nameKo: "에데르 밀리탕", nationality: "브라질", team: "레알 마드리드", position: "CB", birthYear: 1998, number: 3 },
    { name: "David Alaba", nameKo: "다비드 알라바", nationality: "오스트리아", team: "레알 마드리드", position: "CB", birthYear: 1992, number: 4 },
    { name: "Brahim Diaz", nameKo: "브라힘 디아스", nationality: "모로코", team: "레알 마드리드", position: "CAM", birthYear: 1999, number: 21 },
    { name: "Arda Guler", nameKo: "아르다 귈레르", nationality: "터키", team: "레알 마드리드", position: "CAM", birthYear: 2005, number: 15 },
    // 바르셀로나
    { name: "Lamine Yamal", nameKo: "라민 야말", nationality: "스페인", team: "바르셀로나", position: "RW", birthYear: 2007, number: 19 },
    { name: "Pedri", nameKo: "페드리", nationality: "스페인", team: "바르셀로나", position: "CM", birthYear: 2002, number: 8 },
    { name: "Gavi", nameKo: "가비", nationality: "스페인", team: "바르셀로나", position: "CM", birthYear: 2004, number: 6 },
    { name: "Robert Lewandowski", nameKo: "로베르트 레반도프스키", nationality: "폴란드", team: "바르셀로나", position: "ST", birthYear: 1988, number: 9 },
    { name: "Raphinha", nameKo: "하피냐", nationality: "브라질", team: "바르셀로나", position: "RW", birthYear: 1996, number: 11 },
    { name: "Ronald Araujo", nameKo: "로날드 아라우호", nationality: "우루과이", team: "바르셀로나", position: "CB", birthYear: 1999, number: 4 },
    { name: "Marc-Andre ter Stegen", nameKo: "마르크-안드레 테어 슈테겐", nationality: "독일", team: "바르셀로나", position: "GK", birthYear: 1992, number: 1 },
    { name: "Frenkie de Jong", nameKo: "프렝키 더 용", nationality: "네덜란드", team: "바르셀로나", position: "CM", birthYear: 1997, number: 21 },
    { name: "Joao Cancelo", nameKo: "주앙 칸셀루", nationality: "포르투갈", team: "바르셀로나", position: "RB", birthYear: 1994, number: 2 },
    { name: "Jules Kounde", nameKo: "쥘 쿤데", nationality: "프랑스", team: "바르셀로나", position: "CB", birthYear: 1998, number: 23 },
    { name: "Alejandro Balde", nameKo: "알레한드로 발데", nationality: "스페인", team: "바르셀로나", position: "LB", birthYear: 2003, number: 3 },
    { name: "Ferran Torres", nameKo: "페란 토레스", nationality: "스페인", team: "바르셀로나", position: "RW", birthYear: 2000, number: 7 },
    { name: "Joao Felix", nameKo: "주앙 펠릭스", nationality: "포르투갈", team: "바르셀로나", position: "ST", birthYear: 1999, number: 14 },
    { name: "Ilkay Gundogan", nameKo: "일카이 귄도간", nationality: "독일", team: "바르셀로나", position: "CM", birthYear: 1990, number: 22 },
    { name: "Andreas Christensen", nameKo: "안드레아스 크리스텐센", nationality: "덴마크", team: "바르셀로나", position: "CB", birthYear: 1996, number: 15 },
    // 아틀레티코 마드리드
    { name: "Antoine Griezmann", nameKo: "앙투안 그리즈만", nationality: "프랑스", team: "아틀레티코 마드리드", position: "ST", birthYear: 1991, number: 7 },
    { name: "Alvaro Morata", nameKo: "알바로 모라타", nationality: "스페인", team: "아틀레티코 마드리드", position: "ST", birthYear: 1992, number: 9 },
    { name: "Jan Oblak", nameKo: "얀 오블락", nationality: "슬로베니아", team: "아틀레티코 마드리드", position: "GK", birthYear: 1993, number: 13 },
    { name: "Marcos Llorente", nameKo: "마르코스 요렌테", nationality: "스페인", team: "아틀레티코 마드리드", position: "CM", birthYear: 1995, number: 14 },
    { name: "Rodrigo De Paul", nameKo: "로드리고 데 파울", nationality: "아르헨티나", team: "아틀레티코 마드리드", position: "CM", birthYear: 1994, number: 5 },
    { name: "Koke", nameKo: "코게", nationality: "스페인", team: "아틀레티코 마드리드", position: "CM", birthYear: 1992, number: 6 },
    { name: "Jose Maria Gimenez", nameKo: "호세 마리아 히메네스", nationality: "우루과이", team: "아틀레티코 마드리드", position: "CB", birthYear: 1995, number: 2 },
    { name: "Nahuel Molina", nameKo: "나우엘 몰리나", nationality: "아르헨티나", team: "아틀레티코 마드리드", position: "RB", birthYear: 1998, number: 16 },
    { name: "Memphis Depay", nameKo: "멤피스 데파이", nationality: "네덜란드", team: "아틀레티코 마드리드", position: "ST", birthYear: 1994, number: 94 },
    { name: "Samuel Lino", nameKo: "사무엘 리노", nationality: "브라질", team: "아틀레티코 마드리드", position: "LW", birthYear: 2000, number: 12 },
    { name: "Axel Witsel", nameKo: "악셀 비첼", nationality: "벨기에", team: "아틀레티코 마드리드", position: "CB", birthYear: 1989, number: 20 },
    // 레알 소시에다드
    { name: "Mikel Merino", nameKo: "미켈 메리노", nationality: "스페인", team: "레알 소시에다드", position: "CM", birthYear: 1996, number: 8 },
    { name: "Take Kubo", nameKo: "쿠보 다케후사", nationality: "일본", team: "레알 소시에다드", position: "RW", birthYear: 2001, number: 14 },
    { name: "Martin Zubimendi", nameKo: "마르틴 수비멘디", nationality: "스페인", team: "레알 소시에다드", position: "CDM", birthYear: 1999, number: 4 },
    { name: "Alexander Sorloth", nameKo: "알렉산더 쇠를로트", nationality: "노르웨이", team: "레알 소시에다드", position: "ST", birthYear: 1995, number: 19 },
    { name: "Brais Mendez", nameKo: "브라이스 멘데스", nationality: "스페인", team: "레알 소시에다드", position: "CAM", birthYear: 1997, number: 10 },
    { name: "Alex Remiro", nameKo: "알렉스 레미로", nationality: "스페인", team: "레알 소시에다드", position: "GK", birthYear: 1995, number: 1 },
    { name: "Robin Le Normand", nameKo: "로빈 르 노르망", nationality: "스페인", team: "레알 소시에다드", position: "CB", birthYear: 1996, number: 6 },
    // 빌바오
    { name: "Nico Williams", nameKo: "니코 윌리엄스", nationality: "스페인", team: "아틀레틱 빌바오", position: "LW", birthYear: 2002, number: 11 },
    { name: "Inaki Williams", nameKo: "이냐키 윌리엄스", nationality: "스페인", team: "아틀레틱 빌바오", position: "ST", birthYear: 1994, number: 9 },
    { name: "Oihan Sancet", nameKo: "오이한 산세트", nationality: "스페인", team: "아틀레틱 빌바오", position: "CAM", birthYear: 2000, number: 8 },
    { name: "Unai Simon", nameKo: "우나이 시몬", nationality: "스페인", team: "아틀레틱 빌바오", position: "GK", birthYear: 1997, number: 1 },
    { name: "Yuri Berchiche", nameKo: "유리 베르치체", nationality: "스페인", team: "아틀레틱 빌바오", position: "LB", birthYear: 1990, number: 17 },
    // 세비야
    { name: "Youssef En-Nesyri", nameKo: "유세프 엔네시리", nationality: "모로코", team: "세비야", position: "ST", birthYear: 1997, number: 15 },
    { name: "Lucas Ocampos", nameKo: "루카스 오캄포스", nationality: "아르헨티나", team: "세비야", position: "RW", birthYear: 1994, number: 5 },
    { name: "Ivan Rakitic", nameKo: "이반 라키티치", nationality: "크로아티아", team: "세비야", position: "CM", birthYear: 1988, number: 10 },
    { name: "Sergio Ramos", nameKo: "세르히오 라모스", nationality: "스페인", team: "세비야", position: "CB", birthYear: 1986, number: 4 },
    { name: "Jesus Navas", nameKo: "헤수스 나바스", nationality: "스페인", team: "세비야", position: "RB", birthYear: 1985, number: 16 },
    // 베티스
    { name: "Isco", nameKo: "이스코", nationality: "스페인", team: "베티스", position: "CAM", birthYear: 1992, number: 22 },
    { name: "Nabil Fekir", nameKo: "나빌 페키르", nationality: "프랑스", team: "베티스", position: "CAM", birthYear: 1993, number: 8 },
    { name: "Ayoze Perez", nameKo: "아요세 페레스", nationality: "스페인", team: "베티스", position: "ST", birthYear: 1993, number: 10 },
    { name: "Guido Rodriguez", nameKo: "기도 로드리게스", nationality: "아르헨티나", team: "베티스", position: "CDM", birthYear: 1994, number: 5 },
    { name: "Claudio Bravo", nameKo: "클라우디오 브라보", nationality: "칠레", team: "베티스", position: "GK", birthYear: 1983, number: 1 },
    // 비야레알
    { name: "Gerard Moreno", nameKo: "제라르드 모레노", nationality: "스페인", team: "비야레알", position: "ST", birthYear: 1992, number: 7 },
    { name: "Alex Baena", nameKo: "알렉스 바에나", nationality: "스페인", team: "비야레알", position: "CAM", birthYear: 2001, number: 16 },
    { name: "Arnaut Danjuma", nameKo: "아르나우트 단주마", nationality: "네덜란드", team: "비야레알", position: "LW", birthYear: 1997, number: 15 },
    { name: "Juan Foyth", nameKo: "후안 포이스", nationality: "아르헨티나", team: "비야레알", position: "RB", birthYear: 1998, number: 8 },
    { name: "Raul Albiol", nameKo: "라울 알비올", nationality: "스페인", team: "비야레알", position: "CB", birthYear: 1985, number: 3 },
    { name: "Pau Torres", nameKo: "파우 토레스", nationality: "스페인", team: "비야레알", position: "CB", birthYear: 1997, number: 4 },
    // 발렌시아
    { name: "Hugo Duro", nameKo: "우고 두로", nationality: "스페인", team: "발렌시아", position: "ST", birthYear: 1999, number: 9 },
    { name: "Pepelu", nameKo: "페펠루", nationality: "스페인", team: "발렌시아", position: "CM", birthYear: 1998, number: 18 },
    { name: "Giorgi Mamardashvili", nameKo: "기오르기 마마르다슈빌리", nationality: "조지아", team: "발렌시아", position: "GK", birthYear: 2000, number: 25 },
    { name: "Jose Gaya", nameKo: "호세 가야", nationality: "스페인", team: "발렌시아", position: "LB", birthYear: 1995, number: 14 },
    // 셀타 비고
    { name: "Iago Aspas", nameKo: "이아고 아스파스", nationality: "스페인", team: "셀타 비고", position: "ST", birthYear: 1987, number: 10 },
    { name: "Gabri Veiga", nameKo: "가브리 베이가", nationality: "스페인", team: "셀타 비고", position: "CAM", birthYear: 2002, number: 6 },
    { name: "Jorgen Strand Larsen", nameKo: "요르겐 스트란드 라르센", nationality: "노르웨이", team: "셀타 비고", position: "ST", birthYear: 2000, number: 9 },
    // 라스 팔마스
    { name: "Jonathan Viera", nameKo: "조나탄 비에라", nationality: "스페인", team: "라스 팔마스", position: "CAM", birthYear: 1989, number: 21 },
    { name: "Alberto Moleiro", nameKo: "알베르토 몰레이로", nationality: "스페인", team: "라스 팔마스", position: "CAM", birthYear: 2003, number: 10 },
    // 지로나
    { name: "Artem Dovbyk", nameKo: "아르템 도브비크", nationality: "우크라이나", team: "지로나", position: "ST", birthYear: 1997, number: 9 },
    { name: "Savio", nameKo: "사비우", nationality: "브라질", team: "지로나", position: "RW", birthYear: 2004, number: 10 },
    { name: "Aleix Garcia", nameKo: "알레이스 가르시아", nationality: "스페인", team: "지로나", position: "CM", birthYear: 1997, number: 17 },
    { name: "Viktor Tsygankov", nameKo: "빅토르 치간코프", nationality: "우크라이나", team: "지로나", position: "RW", birthYear: 1997, number: 15 },
    { name: "Yan Couto", nameKo: "얀 코우투", nationality: "브라질", team: "지로나", position: "RB", birthYear: 2002, number: 2 },
    { name: "Eric Garcia", nameKo: "에릭 가르시아", nationality: "스페인", team: "지로나", position: "CB", birthYear: 2001, number: 24 },
    { name: "Miguel Gutierrez", nameKo: "미겔 구티에레스", nationality: "스페인", team: "지로나", position: "LB", birthYear: 2001, number: 3 },
    { name: "Daley Blind", nameKo: "데일리 블린트", nationality: "네덜란드", team: "지로나", position: "CB", birthYear: 1990, number: 17 },
    // 오사수나
    { name: "Ante Budimir", nameKo: "안테 부디미르", nationality: "크로아티아", team: "오사수나", position: "ST", birthYear: 1991, number: 17 },
    { name: "Chimy Avila", nameKo: "치미 아빌라", nationality: "아르헨티나", team: "오사수나", position: "ST", birthYear: 1994, number: 9 },
    // 헤타페
    { name: "Borja Mayoral", nameKo: "보르하 마요랄", nationality: "스페인", team: "헤타페", position: "ST", birthYear: 1997, number: 21 },
    { name: "Mason Greenwood", nameKo: "메이슨 그린우드", nationality: "잉글랜드", team: "헤타페", position: "RW", birthYear: 2001, number: 11 },
    // 라요 바예카노
    { name: "Isi Palazon", nameKo: "이시 팔라손", nationality: "스페인", team: "라요 바예카노", position: "RW", birthYear: 1992, number: 21 },
    { name: "Raul de Tomas", nameKo: "라울 데 토마스", nationality: "스페인", team: "라요 바예카노", position: "ST", birthYear: 1994, number: 9 },
    // 마요르카
    { name: "Vedat Muriqi", nameKo: "베다트 무리치", nationality: "코소보", team: "마요르카", position: "ST", birthYear: 1994, number: 17 },
    { name: "Dani Rodriguez", nameKo: "다니 로드리게스", nationality: "스페인", team: "마요르카", position: "CM", birthYear: 1990, number: 14 },
    // 알메리아
    { name: "Leo Baptistao", nameKo: "레오 바프티스타오", nationality: "브라질", team: "알메리아", position: "ST", birthYear: 1992, number: 10 },
    { name: "Luis Suarez", nameKo: "루이스 수아레스", nationality: "콜롬비아", team: "알메리아", position: "ST", birthYear: 1997, number: 9 },
    // 카디스
    { name: "Chris Ramos", nameKo: "크리스 라모스", nationality: "스페인", team: "카디스", position: "ST", birthYear: 2001, number: 19 },
    { name: "Roger Marti", nameKo: "로저 마르티", nationality: "스페인", team: "카디스", position: "ST", birthYear: 1991, number: 9 },
    // 그라나다
    { name: "Myrto Uzuni", nameKo: "미르토 우주니", nationality: "알바니아", team: "그라나다", position: "LW", birthYear: 1995, number: 11 },
    { name: "Lucas Boye", nameKo: "루카스 보예", nationality: "아르헨티나", team: "그라나다", position: "ST", birthYear: 1996, number: 9 },
    // 알라베스
    { name: "Kike Garcia", nameKo: "키게 가르시아", nationality: "스페인", team: "알라베스", position: "ST", birthYear: 1989, number: 9 },
    { name: "Luis Rioja", nameKo: "루이스 리오하", nationality: "스페인", team: "알라베스", position: "LW", birthYear: 1993, number: 11 }
  ],
  "세리에A": [
    // 인터 밀란
    { name: "Lautaro Martinez", nameKo: "라우타로 마르티네스", nationality: "아르헨티나", team: "인터 밀란", position: "ST", birthYear: 1997, number: 10 },
    { name: "Marcus Thuram", nameKo: "마르쿠스 튀랑", nationality: "프랑스", team: "인터 밀란", position: "ST", birthYear: 1997, number: 9 },
    { name: "Nicolo Barella", nameKo: "니콜로 바렐라", nationality: "이탈리아", team: "인터 밀란", position: "CM", birthYear: 1997, number: 23 },
    { name: "Hakan Calhanoglu", nameKo: "하칸 찰하놀루", nationality: "터키", team: "인터 밀란", position: "CM", birthYear: 1994, number: 20 },
    { name: "Alessandro Bastoni", nameKo: "알레산드로 바스토니", nationality: "이탈리아", team: "인터 밀란", position: "CB", birthYear: 1999, number: 95 },
    { name: "Federico Dimarco", nameKo: "페데리코 디마르코", nationality: "이탈리아", team: "인터 밀란", position: "LB", birthYear: 1997, number: 32 },
    { name: "Henrikh Mkhitaryan", nameKo: "헨리흐 므키타리안", nationality: "아르메니아", team: "인터 밀란", position: "CM", birthYear: 1989, number: 22 },
    { name: "Denzel Dumfries", nameKo: "덴젤 뒴프리스", nationality: "네덜란드", team: "인터 밀란", position: "RB", birthYear: 1996, number: 2 },
    { name: "Francesco Acerbi", nameKo: "프란체스코 아체르비", nationality: "이탈리아", team: "인터 밀란", position: "CB", birthYear: 1988, number: 15 },
    { name: "Yann Sommer", nameKo: "얀 조머", nationality: "스위스", team: "인터 밀란", position: "GK", birthYear: 1988, number: 1 },
    { name: "Stefan de Vrij", nameKo: "스테판 더 프레이", nationality: "네덜란드", team: "인터 밀란", position: "CB", birthYear: 1992, number: 6 },
    { name: "Marko Arnautovic", nameKo: "마르코 아르나우토비치", nationality: "오스트리아", team: "인터 밀란", position: "ST", birthYear: 1989, number: 8 },
    // AC 밀란
    { name: "Rafael Leao", nameKo: "하파엘 레앙", nationality: "포르투갈", team: "AC 밀란", position: "LW", birthYear: 1999, number: 10 },
    { name: "Theo Hernandez", nameKo: "테오 에르난데스", nationality: "프랑스", team: "AC 밀란", position: "LB", birthYear: 1997, number: 19 },
    { name: "Mike Maignan", nameKo: "마이크 매냥", nationality: "프랑스", team: "AC 밀란", position: "GK", birthYear: 1995, number: 16 },
    { name: "Christian Pulisic", nameKo: "크리스티안 풀리식", nationality: "미국", team: "AC 밀란", position: "RW", birthYear: 1998, number: 11 },
    { name: "Tijjani Reijnders", nameKo: "티야니 레인더르스", nationality: "네덜란드", team: "AC 밀란", position: "CM", birthYear: 1998, number: 14 },
    { name: "Ruben Loftus-Cheek", nameKo: "루벤 로프터스-치크", nationality: "잉글랜드", team: "AC 밀란", position: "CM", birthYear: 1996, number: 8 },
    { name: "Ismael Bennacer", nameKo: "이스마엘 베나세르", nationality: "알제리", team: "AC 밀란", position: "CDM", birthYear: 1997, number: 4 },
    { name: "Fikayo Tomori", nameKo: "피카요 토모리", nationality: "잉글랜드", team: "AC 밀란", position: "CB", birthYear: 1997, number: 23 },
    { name: "Samuel Chukwueze", nameKo: "사무엘 추크우에제", nationality: "나이지리아", team: "AC 밀란", position: "RW", birthYear: 1999, number: 21 },
    { name: "Davide Calabria", nameKo: "다비데 칼라브리아", nationality: "이탈리아", team: "AC 밀란", position: "RB", birthYear: 1996, number: 2 },
    { name: "Noah Okafor", nameKo: "노아 오카포르", nationality: "스위스", team: "AC 밀란", position: "LW", birthYear: 2000, number: 17 },
    { name: "Olivier Giroud", nameKo: "올리비에 지루", nationality: "프랑스", team: "AC 밀란", position: "ST", birthYear: 1986, number: 9 },
    // 유벤투스
    { name: "Dusan Vlahovic", nameKo: "두샨 블라호비치", nationality: "세르비아", team: "유벤투스", position: "ST", birthYear: 2000, number: 9 },
    { name: "Federico Chiesa", nameKo: "페데리코 키에사", nationality: "이탈리아", team: "유벤투스", position: "RW", birthYear: 1997, number: 7 },
    { name: "Gleison Bremer", nameKo: "글레이송 브레머", nationality: "브라질", team: "유벤투스", position: "CB", birthYear: 1997, number: 3 },
    { name: "Manuel Locatelli", nameKo: "마누엘 로카텔리", nationality: "이탈리아", team: "유벤투스", position: "CM", birthYear: 1998, number: 5 },
    { name: "Adrien Rabiot", nameKo: "아드리앙 라비오", nationality: "프랑스", team: "유벤투스", position: "CM", birthYear: 1995, number: 25 },
    { name: "Wojciech Szczesny", nameKo: "보이치에흐 슈쳉스니", nationality: "폴란드", team: "유벤투스", position: "GK", birthYear: 1990, number: 1 },
    { name: "Filip Kostic", nameKo: "필리프 코스티치", nationality: "세르비아", team: "유벤투스", position: "LW", birthYear: 1992, number: 17 },
    { name: "Alex Sandro", nameKo: "알렉스 산드루", nationality: "브라질", team: "유벤투스", position: "LB", birthYear: 1991, number: 12 },
    { name: "Danilo", nameKo: "다닐루", nationality: "브라질", team: "유벤투스", position: "RB", birthYear: 1991, number: 6 },
    { name: "Kenan Yildiz", nameKo: "케난 이을디즈", nationality: "터키", team: "유벤투스", position: "LW", birthYear: 2005, number: 10 },
    { name: "Timothy Weah", nameKo: "티모시 웨아", nationality: "미국", team: "유벤투스", position: "RW", birthYear: 2000, number: 22 },
    // 나폴리
    { name: "Victor Osimhen", nameKo: "빅터 오시멘", nationality: "나이지리아", team: "나폴리", position: "ST", birthYear: 1998, number: 9 },
    { name: "Khvicha Kvaratskhelia", nameKo: "크비차 크바라츠헬리아", nationality: "조지아", team: "나폴리", position: "LW", birthYear: 2001, number: 77 },
    { name: "Giovanni Di Lorenzo", nameKo: "조반니 디 로렌초", nationality: "이탈리아", team: "나폴리", position: "RB", birthYear: 1993, number: 22 },
    { name: "Kim Min-jae", nameKo: "김민재", nationality: "대한민국", team: "나폴리", position: "CB", birthYear: 1996, number: 3 },
    { name: "Stanislav Lobotka", nameKo: "스타니슬라프 로보트카", nationality: "슬로바키아", team: "나폴리", position: "CDM", birthYear: 1994, number: 68 },
    { name: "Piotr Zielinski", nameKo: "피오트르 지엘린스키", nationality: "폴란드", team: "나폴리", position: "CM", birthYear: 1994, number: 20 },
    { name: "Amir Rrahmani", nameKo: "아미르 라흐마니", nationality: "코소보", team: "나폴리", position: "CB", birthYear: 1994, number: 13 },
    { name: "Alex Meret", nameKo: "알렉스 메레트", nationality: "이탈리아", team: "나폴리", position: "GK", birthYear: 1997, number: 1 },
    { name: "Matteo Politano", nameKo: "마테오 폴리타노", nationality: "이탈리아", team: "나폴리", position: "RW", birthYear: 1993, number: 21 },
    { name: "Giovanni Simeone", nameKo: "조반니 시메오네", nationality: "아르헨티나", team: "나폴리", position: "ST", birthYear: 1995, number: 18 },
    // AS 로마
    { name: "Paulo Dybala", nameKo: "파울로 디발라", nationality: "아르헨티나", team: "AS 로마", position: "CAM", birthYear: 1993, number: 21 },
    { name: "Romelu Lukaku", nameKo: "로멜루 루카쿠", nationality: "벨기에", team: "AS 로마", position: "ST", birthYear: 1993, number: 9 },
    { name: "Lorenzo Pellegrini", nameKo: "로렌초 펠레그리니", nationality: "이탈리아", team: "AS 로마", position: "CAM", birthYear: 1996, number: 7 },
    { name: "Gianluca Mancini", nameKo: "지안루카 만치니", nationality: "이탈리아", team: "AS 로마", position: "CB", birthYear: 1996, number: 23 },
    { name: "Chris Smalling", nameKo: "크리스 스몰링", nationality: "잉글랜드", team: "AS 로마", position: "CB", birthYear: 1989, number: 6 },
    { name: "Rui Patricio", nameKo: "루이 파트리시우", nationality: "포르투갈", team: "AS 로마", position: "GK", birthYear: 1988, number: 1 },
    { name: "Leandro Paredes", nameKo: "레안드로 파레데스", nationality: "아르헨티나", team: "AS 로마", position: "CM", birthYear: 1994, number: 16 },
    { name: "Stephan El Shaarawy", nameKo: "스테판 엘 샤라위", nationality: "이탈리아", team: "AS 로마", position: "LW", birthYear: 1992, number: 92 },
    // 라치오
    { name: "Ciro Immobile", nameKo: "치로 임모빌레", nationality: "이탈리아", team: "라치오", position: "ST", birthYear: 1990, number: 17 },
    { name: "Sergej Milinkovic-Savic", nameKo: "세르게이 밀린코비치-사비치", nationality: "세르비아", team: "라치오", position: "CM", birthYear: 1995, number: 21 },
    { name: "Luis Alberto", nameKo: "루이스 알베르토", nationality: "스페인", team: "라치오", position: "CAM", birthYear: 1992, number: 10 },
    { name: "Pedro", nameKo: "페드로", nationality: "스페인", team: "라치오", position: "RW", birthYear: 1987, number: 9 },
    { name: "Ivan Provedel", nameKo: "이반 프로베델", nationality: "이탈리아", team: "라치오", position: "GK", birthYear: 1994, number: 1 },
    { name: "Adam Marusic", nameKo: "아담 마루시치", nationality: "몬테네그로", team: "라치오", position: "RB", birthYear: 1992, number: 77 },
    { name: "Felipe Anderson", nameKo: "펠리피 안데르송", nationality: "브라질", team: "라치오", position: "RW", birthYear: 1993, number: 7 },
    { name: "Mattia Zaccagni", nameKo: "마티아 자카니", nationality: "이탈리아", team: "라치오", position: "LW", birthYear: 1995, number: 20 },
    // 아탈란타
    { name: "Ademola Lookman", nameKo: "아데몰라 루크만", nationality: "나이지리아", team: "아탈란타", position: "LW", birthYear: 1997, number: 11 },
    { name: "Gianluca Scamacca", nameKo: "지안루카 스카마카", nationality: "이탈리아", team: "아탈란타", position: "ST", birthYear: 1999, number: 90 },
    { name: "Teun Koopmeiners", nameKo: "튠 콥마이너르스", nationality: "네덜란드", team: "아탈란타", position: "CM", birthYear: 1998, number: 7 },
    { name: "Ederson", nameKo: "에데르송", nationality: "브라질", team: "아탈란타", position: "CM", birthYear: 1999, number: 13 },
    { name: "Mario Pasalic", nameKo: "마리오 파살리치", nationality: "크로아티아", team: "아탈란타", position: "CAM", birthYear: 1995, number: 88 },
    { name: "Juan Musso", nameKo: "후안 무소", nationality: "아르헨티나", team: "아탈란타", position: "GK", birthYear: 1994, number: 1 },
    { name: "Rafael Toloi", nameKo: "라파엘 톨로이", nationality: "이탈리아", team: "아탈란타", position: "CB", birthYear: 1990, number: 2 },
    // 피오렌티나
    { name: "Nico Gonzalez", nameKo: "니코 곤살레스", nationality: "아르헨티나", team: "피오렌티나", position: "RW", birthYear: 1998, number: 10 },
    { name: "Giacomo Bonaventura", nameKo: "자코모 보나벤투라", nationality: "이탈리아", team: "피오렌티나", position: "CM", birthYear: 1989, number: 5 },
    { name: "Luka Jovic", nameKo: "루카 요비치", nationality: "세르비아", team: "피오렌티나", position: "ST", birthYear: 1997, number: 7 },
    { name: "Pietro Terracciano", nameKo: "피에트로 테라치아노", nationality: "이탈리아", team: "피오렌티나", position: "GK", birthYear: 1990, number: 1 },
    { name: "Nikola Milenkovic", nameKo: "니콜라 밀렌코비치", nationality: "세르비아", team: "피오렌티나", position: "CB", birthYear: 1997, number: 4 },
    { name: "Riccardo Sottil", nameKo: "리카르도 소틸", nationality: "이탈리아", team: "피오렌티나", position: "LW", birthYear: 1999, number: 32 },
    { name: "Sofyan Amrabat", nameKo: "소피안 암라바트", nationality: "모로코", team: "피오렌티나", position: "CDM", birthYear: 1996, number: 4 },
    // 볼로냐
    { name: "Joshua Zirkzee", nameKo: "조슈아 지르크제", nationality: "네덜란드", team: "볼로냐", position: "ST", birthYear: 2001, number: 9 },
    { name: "Riccardo Orsolini", nameKo: "리카르도 오르솔리니", nationality: "이탈리아", team: "볼로냐", position: "RW", birthYear: 1997, number: 7 },
    { name: "Lewis Ferguson", nameKo: "루이스 퍼거슨", nationality: "스코틀랜드", team: "볼로냐", position: "CM", birthYear: 1999, number: 19 },
    { name: "Remo Freuler", nameKo: "레모 프로일러", nationality: "스위스", team: "볼로냐", position: "CM", birthYear: 1992, number: 8 },
    { name: "Sam Beukema", nameKo: "샘 뵈케마", nationality: "네덜란드", team: "볼로냐", position: "CB", birthYear: 1998, number: 31 },
    // 토리노
    { name: "Duvan Zapata", nameKo: "두반 사파타", nationality: "콜롬비아", team: "토리노", position: "ST", birthYear: 1991, number: 91 },
    { name: "Antonio Sanabria", nameKo: "안토니오 사나브리아", nationality: "파라과이", team: "토리노", position: "ST", birthYear: 1996, number: 9 },
    { name: "Nikola Vlasic", nameKo: "니콜라 블라시치", nationality: "크로아티아", team: "토리노", position: "CAM", birthYear: 1997, number: 10 },
    { name: "Vanja Milinkovic-Savic", nameKo: "반야 밀린코비치-사비치", nationality: "세르비아", team: "토리노", position: "GK", birthYear: 1997, number: 32 },
    { name: "Alessandro Buongiorno", nameKo: "알레산드로 부온지오르노", nationality: "이탈리아", team: "토리노", position: "CB", birthYear: 1999, number: 4 },
    // 몬자
    { name: "Gianluca Caprari", nameKo: "지안루카 카프라리", nationality: "이탈리아", team: "몬자", position: "ST", birthYear: 1993, number: 10 },
    { name: "Andrea Colpani", nameKo: "안드레아 콜파니", nationality: "이탈리아", team: "몬자", position: "CAM", birthYear: 1999, number: 28 },
    { name: "Matteo Pessina", nameKo: "마테오 페시나", nationality: "이탈리아", team: "몬자", position: "CM", birthYear: 1997, number: 32 },
    // 젠노아
    { name: "Albert Gudmundsson", nameKo: "알베르트 구드문드손", nationality: "아이슬란드", team: "제노아", position: "CAM", birthYear: 1997, number: 11 },
    { name: "Mateo Retegui", nameKo: "마테오 레테기", nationality: "아르헨티나", team: "제노아", position: "ST", birthYear: 1999, number: 19 },
    // 우디네세
    { name: "Gerard Deulofeu", nameKo: "제라르드 데울로페우", nationality: "스페인", team: "우디네세", position: "LW", birthYear: 1994, number: 10 },
    { name: "Lazar Samardzic", nameKo: "라자르 사마르지치", nationality: "세르비아", team: "우디네세", position: "CAM", birthYear: 2002, number: 24 },
    // 사수올로
    { name: "Domenico Berardi", nameKo: "도메니코 베라르디", nationality: "이탈리아", team: "사수올로", position: "RW", birthYear: 1994, number: 25 },
    { name: "Armand Lauriente", nameKo: "아르망 로리앙트", nationality: "프랑스", team: "사수올로", position: "LW", birthYear: 1998, number: 21 },
    // 레체
    { name: "Patrick Dorgu", nameKo: "패트릭 도르구", nationality: "덴마크", team: "레체", position: "LB", birthYear: 2004, number: 13 },
    // 엠폴리
    { name: "Francesco Caputo", nameKo: "프란체스코 카푸토", nationality: "이탈리아", team: "엠폴리", position: "ST", birthYear: 1987, number: 9 },
    // 프로시노네
    { name: "Nadir Zortea", nameKo: "나디르 조르테아", nationality: "이탈리아", team: "프로시노네", position: "RB", birthYear: 1999, number: 17 },
    // 칼리아리
    { name: "Leonardo Pavoletti", nameKo: "레오나르도 파볼레티", nationality: "이탈리아", team: "칼리아리", position: "ST", birthYear: 1988, number: 30 },
    { name: "Nicolas Viola", nameKo: "니콜라스 비올라", nationality: "이탈리아", team: "칼리아리", position: "CM", birthYear: 1989, number: 10 },
    // 헬라스 베로나
    { name: "Ondrej Duda", nameKo: "온드레이 두다", nationality: "슬로바키아", team: "헬라스 베로나", position: "CAM", birthYear: 1994, number: 16 },
    { name: "Thomas Henry", nameKo: "토마스 앙리", nationality: "프랑스", team: "헬라스 베로나", position: "ST", birthYear: 1994, number: 29 },
    // 살레르니타나
    { name: "Boulaye Dia", nameKo: "불라예 디아", nationality: "세네갈", team: "살레르니타나", position: "ST", birthYear: 1996, number: 9 },
    { name: "Antonio Candreva", nameKo: "안토니오 칸드레바", nationality: "이탈리아", team: "살레르니타나", position: "RM", birthYear: 1987, number: 87 }
  ],
  "리그1": [
    // 파리 생제르맹
    { name: "Ousmane Dembele", nameKo: "우스만 뎀벨레", nationality: "프랑스", team: "파리 생제르맹", position: "RW", birthYear: 1997, number: 10 },
    { name: "Randal Kolo Muani", nameKo: "랑달 콜로 무아니", nationality: "프랑스", team: "파리 생제르맹", position: "ST", birthYear: 1998, number: 23 },
    { name: "Achraf Hakimi", nameKo: "아크라프 하키미", nationality: "모로코", team: "파리 생제르맹", position: "RB", birthYear: 1998, number: 2 },
    { name: "Marquinhos", nameKo: "마르키뉴스", nationality: "브라질", team: "파리 생제르맹", position: "CB", birthYear: 1994, number: 5 },
    { name: "Gianluigi Donnarumma", nameKo: "지안루이지 돈나루마", nationality: "이탈리아", team: "파리 생제르맹", position: "GK", birthYear: 1999, number: 1 },
    { name: "Vitinha", nameKo: "비티냐", nationality: "포르투갈", team: "파리 생제르맹", position: "CM", birthYear: 2000, number: 17 },
    { name: "Warren Zaire-Emery", nameKo: "워렌 자이르-에메리", nationality: "프랑스", team: "파리 생제르맹", position: "CM", birthYear: 2006, number: 33 },
    { name: "Bradley Barcola", nameKo: "브래들리 바르콜라", nationality: "프랑스", team: "파리 생제르맹", position: "LW", birthYear: 2002, number: 29 },
    { name: "Lucas Hernandez", nameKo: "루카스 에르난데스", nationality: "프랑스", team: "파리 생제르맹", position: "CB", birthYear: 1996, number: 21 },
    { name: "Fabian Ruiz", nameKo: "파비안 루이스", nationality: "스페인", team: "파리 생제르맹", position: "CM", birthYear: 1996, number: 8 },
    { name: "Presnel Kimpembe", nameKo: "프레스넬 킴펨베", nationality: "프랑스", team: "파리 생제르맹", position: "CB", birthYear: 1995, number: 3 },
    { name: "Nuno Mendes", nameKo: "누누 멘데스", nationality: "포르투갈", team: "파리 생제르맹", position: "LB", birthYear: 2002, number: 25 },
    { name: "Manuel Ugarte", nameKo: "마누엘 우가르테", nationality: "우루과이", team: "파리 생제르맹", position: "CDM", birthYear: 2001, number: 4 },
    { name: "Lee Kang-in", nameKo: "이강인", nationality: "대한민국", team: "파리 생제르맹", position: "CAM", birthYear: 2001, number: 19 },
    { name: "Gonçalo Ramos", nameKo: "곤살루 하무스", nationality: "포르투갈", team: "파리 생제르맹", position: "ST", birthYear: 2001, number: 9 },
    // 마르세유
    { name: "Pierre-Emerick Aubameyang", nameKo: "피에르-에메릭 오바메양", nationality: "가봉", team: "올림피크 마르세유", position: "ST", birthYear: 1989, number: 10 },
    { name: "Matteo Guendouzi", nameKo: "마테오 겐두지", nationality: "프랑스", team: "올림피크 마르세유", position: "CM", birthYear: 1999, number: 6 },
    { name: "Jordan Veretout", nameKo: "조르당 베레투", nationality: "프랑스", team: "올림피크 마르세유", position: "CM", birthYear: 1993, number: 27 },
    { name: "Jonathan Clauss", nameKo: "조나탕 클로스", nationality: "프랑스", team: "올림피크 마르세유", position: "RB", birthYear: 1992, number: 7 },
    { name: "Pau Lopez", nameKo: "파우 로페스", nationality: "스페인", team: "올림피크 마르세유", position: "GK", birthYear: 1994, number: 16 },
    { name: "Chancel Mbemba", nameKo: "샹셀 음벰바", nationality: "콩고민주공화국", team: "올림피크 마르세유", position: "CB", birthYear: 1994, number: 99 },
    { name: "Amine Harit", nameKo: "아민 아리트", nationality: "모로코", team: "올림피크 마르세유", position: "CAM", birthYear: 1997, number: 11 },
    { name: "Iliman Ndiaye", nameKo: "일리만 은디아예", nationality: "세네갈", team: "올림피크 마르세유", position: "ST", birthYear: 2000, number: 10 },
    // 모나코
    { name: "Wissam Ben Yedder", nameKo: "위삼 벤 예데르", nationality: "프랑스", team: "AS 모나코", position: "ST", birthYear: 1990, number: 9 },
    { name: "Youssouf Fofana", nameKo: "유수프 포파나", nationality: "프랑스", team: "AS 모나코", position: "CM", birthYear: 1999, number: 19 },
    { name: "Aleksandr Golovin", nameKo: "알렉산드르 골로빈", nationality: "러시아", team: "AS 모나코", position: "CAM", birthYear: 1996, number: 17 },
    { name: "Takumi Minamino", nameKo: "미나미노 다쿠미", nationality: "일본", team: "AS 모나코", position: "LW", birthYear: 1995, number: 18 },
    { name: "Guillermo Maripan", nameKo: "기예르모 마리판", nationality: "칠레", team: "AS 모나코", position: "CB", birthYear: 1994, number: 3 },
    { name: "Vanderson", nameKo: "반데르송", nationality: "브라질", team: "AS 모나코", position: "RB", birthYear: 2001, number: 2 },
    { name: "Breel Embolo", nameKo: "브릴 엠볼로", nationality: "스위스", team: "AS 모나코", position: "ST", birthYear: 1997, number: 36 },
    { name: "Denis Zakaria", nameKo: "데니스 자카리아", nationality: "스위스", team: "AS 모나코", position: "CDM", birthYear: 1996, number: 33 },
    { name: "Eliesse Ben Seghir", nameKo: "엘리에스 벤 세기르", nationality: "모로코", team: "AS 모나코", position: "LW", birthYear: 2005, number: 47 },
    // 릴
    { name: "Jonathan David", nameKo: "조나단 데이비드", nationality: "캐나다", team: "릴", position: "ST", birthYear: 2000, number: 9 },
    { name: "Yusuf Yazici", nameKo: "유수프 야즈즈", nationality: "터키", team: "릴", position: "CAM", birthYear: 1997, number: 12 },
    { name: "Remy Cabella", nameKo: "레미 카벨라", nationality: "프랑스", team: "릴", position: "CAM", birthYear: 1990, number: 7 },
    { name: "Benjamin Andre", nameKo: "벵자맹 앙드레", nationality: "프랑스", team: "릴", position: "CDM", birthYear: 1990, number: 21 },
    { name: "Lucas Chevalier", nameKo: "루카스 슈발리에", nationality: "프랑스", team: "릴", position: "GK", birthYear: 2001, number: 30 },
    { name: "Tiago Santos", nameKo: "티아구 산투스", nationality: "포르투갈", team: "릴", position: "RB", birthYear: 2002, number: 28 },
    { name: "Leny Yoro", nameKo: "레니 요로", nationality: "프랑스", team: "릴", position: "CB", birthYear: 2005, number: 15 },
    { name: "Gabriel Gudmundsson", nameKo: "가브리엘 구드문드손", nationality: "스웨덴", team: "릴", position: "LB", birthYear: 1999, number: 3 },
    // 리옹
    { name: "Alexandre Lacazette", nameKo: "알렉상드르 라카제트", nationality: "프랑스", team: "올림피크 리옹", position: "ST", birthYear: 1991, number: 10 },
    { name: "Rayan Cherki", nameKo: "라얀 셰르키", nationality: "프랑스", team: "올림피크 리옹", position: "CAM", birthYear: 2003, number: 18 },
    { name: "Corentin Tolisso", nameKo: "코랑탱 톨리소", nationality: "프랑스", team: "올림피크 리옹", position: "CM", birthYear: 1994, number: 88 },
    { name: "Nicolas Tagliafico", nameKo: "니콜라스 탈리아피코", nationality: "아르헨티나", team: "올림피크 리옹", position: "LB", birthYear: 1992, number: 3 },
    { name: "Anthony Lopes", nameKo: "안토니 로페스", nationality: "포르투갈", team: "올림피크 리옹", position: "GK", birthYear: 1990, number: 1 },
    { name: "Jake O'Brien", nameKo: "제이크 오브라이언", nationality: "아일랜드", team: "올림피크 리옹", position: "CB", birthYear: 2001, number: 5 },
    { name: "Gift Orban", nameKo: "기프트 오르반", nationality: "나이지리아", team: "올림피크 리옹", position: "ST", birthYear: 2002, number: 14 },
    { name: "Mama Balde", nameKo: "마마 발데", nationality: "기니비사우", team: "올림피크 리옹", position: "LW", birthYear: 1996, number: 7 },
    // 렌
    { name: "Amine Gouiri", nameKo: "아민 구이리", nationality: "프랑스", team: "렌", position: "ST", birthYear: 2000, number: 11 },
    { name: "Martin Terrier", nameKo: "마르탱 테리에", nationality: "프랑스", team: "렌", position: "LW", birthYear: 1997, number: 7 },
    { name: "Benjamin Bourigeaud", nameKo: "벵자맹 부리고", nationality: "프랑스", team: "렌", position: "CM", birthYear: 1994, number: 14 },
    { name: "Steve Mandanda", nameKo: "스테브 망당다", nationality: "프랑스", team: "렌", position: "GK", birthYear: 1985, number: 16 },
    { name: "Arnaud Kalimuendo", nameKo: "아르노 칼리무엔도", nationality: "프랑스", team: "렌", position: "ST", birthYear: 2002, number: 22 },
    { name: "Desire Doue", nameKo: "데지레 두에", nationality: "프랑스", team: "렌", position: "CAM", birthYear: 2005, number: 14 },
    // 니스
    { name: "Terem Moffi", nameKo: "테렘 모피", nationality: "나이지리아", team: "니스", position: "ST", birthYear: 1999, number: 9 },
    { name: "Ross Barkley", nameKo: "로스 바클리", nationality: "잉글랜드", team: "니스", position: "CM", birthYear: 1993, number: 8 },
    { name: "Nicolas Pepe", nameKo: "니콜라 페페", nationality: "코트디부아르", team: "니스", position: "RW", birthYear: 1995, number: 18 },
    { name: "Marcin Bulka", nameKo: "마르친 불카", nationality: "폴란드", team: "니스", position: "GK", birthYear: 1999, number: 25 },
    { name: "Jean-Clair Todibo", nameKo: "장-클레어 토디보", nationality: "프랑스", team: "니스", position: "CB", birthYear: 1999, number: 6 },
    { name: "Jeremie Boga", nameKo: "제레미 보가", nationality: "코트디부아르", team: "니스", position: "LW", birthYear: 1997, number: 7 },
    // 랑스
    { name: "Folarin Balogun", nameKo: "폴라린 발로건", nationality: "미국", team: "랑스", position: "ST", birthYear: 2001, number: 9 },
    { name: "Marshall Munetsi", nameKo: "마샬 무네치", nationality: "짐바브웨", team: "랑스", position: "CM", birthYear: 1996, number: 19 },
    { name: "Martin Adeline", nameKo: "마르탱 아델린", nationality: "프랑스", team: "랑스", position: "CM", birthYear: 2003, number: 14 },
    { name: "Yehvann Diouf", nameKo: "예반 디우프", nationality: "프랑스", team: "랑스", position: "GK", birthYear: 1999, number: 1 },
    { name: "Will Still", nameKo: "윌 스틸", nationality: "벨기에", team: "랑스", position: "CB", birthYear: 1993, number: 4 },
    // 스트라스부르
    { name: "Habib Diarra", nameKo: "아비브 디아라", nationality: "말리", team: "스트라스부르", position: "CM", birthYear: 2004, number: 8 },
    { name: "Lebo Mothiba", nameKo: "레보 모티바", nationality: "남아프리카공화국", team: "스트라스부르", position: "ST", birthYear: 1996, number: 10 },
    { name: "Kevin Gameiro", nameKo: "케빈 가메이루", nationality: "프랑스", team: "스트라스부르", position: "ST", birthYear: 1987, number: 7 },
    // 낭트
    { name: "Mostafa Mohamed", nameKo: "모스타파 무함메드", nationality: "이집트", team: "낭트", position: "ST", birthYear: 1997, number: 9 },
    { name: "Moses Simon", nameKo: "모세스 시몬", nationality: "나이지리아", team: "낭트", position: "LW", birthYear: 1995, number: 27 },
    { name: "Pedro Chirivella", nameKo: "페드로 치리벨라", nationality: "스페인", team: "낭트", position: "CM", birthYear: 1997, number: 6 },
    { name: "Alban Lafont", nameKo: "알방 라퐁", nationality: "프랑스", team: "낭트", position: "GK", birthYear: 1999, number: 1 },
    // 몽펠리에
    { name: "Elye Wahi", nameKo: "엘리 와이", nationality: "프랑스", team: "몽펠리에", position: "ST", birthYear: 2003, number: 9 },
    { name: "Teji Savanier", nameKo: "테지 사바니에", nationality: "프랑스", team: "몽펠리에", position: "CM", birthYear: 1991, number: 11 },
    { name: "Jordan Ferri", nameKo: "조르당 페리", nationality: "프랑스", team: "몽펠리에", position: "CM", birthYear: 1992, number: 14 },
    { name: "Arnaud Nordin", nameKo: "아르노 노르댕", nationality: "프랑스", team: "몽펠리에", position: "LW", birthYear: 1998, number: 20 },
    // 브레스트
    { name: "Martin Satriano", nameKo: "마르틴 사트리아노", nationality: "우루과이", team: "브레스트", position: "ST", birthYear: 2001, number: 9 },
    { name: "Steve Mounie", nameKo: "스테브 무니에", nationality: "베냉", team: "브레스트", position: "ST", birthYear: 1994, number: 17 },
    { name: "Pierre Lees-Melou", nameKo: "피에르 레-멜루", nationality: "프랑스", team: "브레스트", position: "CM", birthYear: 1993, number: 8 },
    { name: "Marco Bizot", nameKo: "마르코 비조트", nationality: "네덜란드", team: "브레스트", position: "GK", birthYear: 1991, number: 1 },
    { name: "Romain Del Castillo", nameKo: "로맹 델 카스티요", nationality: "프랑스", team: "브레스트", position: "RW", birthYear: 1996, number: 7 },
    // 툴루즈
    { name: "Thijs Dallinga", nameKo: "테이스 달링하", nationality: "네덜란드", team: "툴루즈", position: "ST", birthYear: 2000, number: 9 },
    { name: "Zakaria Aboukhlal", nameKo: "자카리아 아부클랄", nationality: "모로코", team: "툴루즈", position: "LW", birthYear: 2000, number: 15 },
    { name: "Fares Chaibi", nameKo: "파레스 샤이비", nationality: "알제리", team: "툴루즈", position: "CAM", birthYear: 2003, number: 10 },
    { name: "Guillaume Restes", nameKo: "기욤 레스트", nationality: "프랑스", team: "툴루즈", position: "GK", birthYear: 2005, number: 1 },
    { name: "Aron Donnum", nameKo: "아론 도눔", nationality: "노르웨이", team: "툴루즈", position: "LW", birthYear: 1998, number: 17 },
    // 르아브르
    { name: "Andre Ayew", nameKo: "앙드레 아예", nationality: "가나", team: "르아브르", position: "ST", birthYear: 1989, number: 10 },
    { name: "Nabil Alioui", nameKo: "나빌 알리우이", nationality: "프랑스", team: "르아브르", position: "ST", birthYear: 2002, number: 9 },
    { name: "Arouna Sangante", nameKo: "아루나 상간테", nationality: "말리", team: "르아브르", position: "RB", birthYear: 2001, number: 2 },
    // 클레르몽
    { name: "Mohamed Bayo", nameKo: "모하메드 바요", nationality: "기니", team: "클레르몽", position: "ST", birthYear: 1998, number: 9 },
    { name: "Elbasan Rashani", nameKo: "엘바산 라샤니", nationality: "코소보", team: "클레르몽", position: "RW", birthYear: 1993, number: 7 },
    { name: "Johan Gastien", nameKo: "요한 가스티앵", nationality: "프랑스", team: "클레르몽", position: "CM", birthYear: 1988, number: 27 },
    // 로리앙
    { name: "Bamba Dieng", nameKo: "밤바 디엥", nationality: "세네갈", team: "로리앙", position: "ST", birthYear: 2000, number: 9 },
    { name: "Dango Ouattara", nameKo: "당고 와타라", nationality: "부르키나파소", team: "로리앙", position: "RW", birthYear: 2002, number: 11 },
    { name: "Darlin Yongwa", nameKo: "달린 용와", nationality: "카메룬", team: "로리앙", position: "CM", birthYear: 2002, number: 25 },
    // 멧
    { name: "Matthieu Udol", nameKo: "마티외 우돌", nationality: "프랑스", team: "멧", position: "LB", birthYear: 1996, number: 22 },
    { name: "Georges Mikautadze", nameKo: "게오르게스 미카우타제", nationality: "조지아", team: "멧", position: "ST", birthYear: 2000, number: 69 },
    { name: "Lamine Camara", nameKo: "라민 카마라", nationality: "세네갈", team: "멧", position: "CM", birthYear: 2004, number: 8 }
  ]
};

// 현재 선택된 리그의 선수 목록
let players = [];
